=== AKAIsmael/movsim/consumption/src/main/resources/config/movsimConsumptionModel.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- ##################################################################### -->
<!-- DTD Validation Grammar for Movsim Consumption Model                   -->
<!-- (c) 2012 Arne Kesting, Martin Treiber                                 -->
<!-- ##################################################################### -->


<!-- ############################################################################## -->
<!-- Short reference for xml dtd syntax -->
<!-- http://www.herongyang.com/XML/DTD-Syntax-of-DTD-Statements.html -->
<!-- http://www.mihaiu.name/2005/xml-dtd-reference/ -->
<!-- <!ELEMENT> this tag is used to define an XML element type name and its permissible sub-elements;  -->
<!-- <!ELEMEMT elementName EMPTY>  : this element cannot have content, but it can have attributes -->
<!-- Element can have children but it cannot contain text (with the exception of whitespace): -->
<!-- <!ELEMENT elementName (child1, child2)> : element's children are specified using a sequence list thus they must appear in the specified order -->
<!-- <!ELEMENT elementName (child1 | child2)> : element's children are specified using a mutually exclusive choice list -->
<!-- Cardinality operators: ?="0 or 1"; *="0 to n";+="1 to n" -->
<!-- <!ATTLIST>  defines the attributes of an XML element (permissible and default values) -->
<!-- <!ATTLIST AnElement an_attribute CDATA #REQUIRED> : the attribute *must* be present in the XML document (is required) -->
<!-- <!ATTLIST AnElement an_attribute CDATA #IMPLIED> : the attribute is optional -->
<!-- <!ATTLIST AnElement an_attribute CDATA "value"> : attribute is optional and it has a default value; a validating parser will supply the default value if the attribute is not specified in the respective element -->
<!-- <!ATTLIST Test6 an_attribute (value1 | value2) #IMPLIED> : the attribute is optional but it can only have values from a predefined list -->
<!-- ############################################################################## -->
<!-- Here NMTOKEN is used for "normal" values, (true|false) indicate defined boolean values and CDATA is used when parsing allows also for constructs like "1/3.6" -->
<!-- ############################################################################## -->


<!-- general remarks: -->
<!-- all parameter values are expected in SI units. Otherwise the attribute's name is indicating the unit explicitely -->

<!ELEMENT movsim (batch?, consumption) >


<!-- ##################################################################### -->
<!-- Batch                                                                 -->
<!-- ##################################################################### -->
<!ELEMENT batch (data+) >
<!ATTLIST batch
>

<!ELEMENT data (columns, conversions) >
<!ATTLIST data
inputfile  CDATA   #REQUIRED
outputfile  CDATA   #REQUIRED
model  CDATA   #REQUIRED
>

<!ELEMENT columns EMPTY >
<!ATTLIST columns
time  NMTOKEN   #REQUIRED
speed NMTOKEN   #REQUIRED
acceleration  NMTOKEN   #REQUIRED
gradient  NMTOKEN   #REQUIRED
position NMTOKEN "-1"
>

<!ELEMENT conversions EMPTY >
<!ATTLIST conversions
time CDATA  ""
speed NMTOKEN "1"
acceleration  NMTOKEN  "1"
gradient  NMTOKEN "1"
position NMTOKEN "1"
>


<!-- ##################################################################### -->
<!-- Consumption Model                                                -->
<!-- ##################################################################### -->

<!ELEMENT consumption (model+) >

<!ATTLIST consumption
>

<!ELEMENT model (vehicle,(engineCombustionMap|engineConstantMap),rotationModel) >


<!ATTLIST model
  label   CDATA   #REQUIRED
  output  (true|false) "false"
>

<!ELEMENT vehicle EMPTY >
<!ATTLIST vehicle
  mass                    NMTOKEN "1500"
  cross_section_surface   NMTOKEN "2.2"
  cd_value                NMTOKEN "0.32"
  electric_power          NMTOKEN "2000"
  const_friction          NMTOKEN "0.0145"
  v_friction              NMTOKEN "0"
>

<!ELEMENT engineCombustionMap EMPTY >
<!ATTLIST engineCombustionMap
  max_power_kW  NMTOKEN "90"
  cylinder_vol_l  NMTOKEN "1.4"
  idle_cons_rate_linvh NMTOKEN "0.6"
  cspec_min_g_per_kwh NMTOKEN "212"
  pe_min_bar NMTOKEN "1"
  pe_max_bar NMTOKEN "19"
>

<!ELEMENT engineConstantMap EMPTY >
<!ATTLIST engine
  max_power_kW  NMTOKEN "90"
  idle_cons_rate_linvh NMTOKEN "0.6"
  cspec_min_g_per_kwh NMTOKEN "212"
>

<!ELEMENT rotationModel (gearRatio+) >
<!ATTLIST rotationModel
  idle_rotation_rate_invmin NMTOKEN "1000"
  max_rotation_rate_invmin NMTOKEN "6000"
  dynamic_tyre_radius     NMTOKEN "0.3113"
>

<!ELEMENT gearRatio EMPTY >
<!ATTLIST gearRatio
  phi   NMTOKEN  #REQUIRED
>

=== AKAIsmael/movsim/consumption/data/sim/consumption_sim.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movsim SYSTEM "movsimconsumptionmodel.dtd">

<movsim>

    <batch>
        <data inputfile="city_example.car.route_main.000002.dat" outputfile="city_example.car.route_main.000002.AudiA3.csv" model="AudiA3">
            <columns time="1" speed="6" acceleration="7" gradient="14"/>
            <conversions /> 
        </data>

        <data inputfile="city_example.car.route_main.000003.dat" outputfile="city_example.car.route_main.000003.AudiA3.csv" model="AudiA3">
            <columns time="1" speed="6" acceleration="7" gradient="14"/>
            <conversions /> 
        </data>

        <data inputfile="city_example.car.route_main.000004.dat" outputfile="city_example.car.route_main.000004.AudiA3.csv" model="AudiA3">
            <columns time="1" speed="6" acceleration="7" gradient="14"/>
            <conversions /> 
        </data>
    </batch>


    <consumption>
        <model label="AudiA3" output="true">
            <vehicle mass="1000" cross_section_surface="2.13" cd_value="0.32" const_friction="0.015" v_friction="0" electric_power="1500" />
            <engine max_power_kW="100" cylinder_vol_l="1.8" idle_cons_rate_linvh="0.8" cspec_min_g_per_kwh="225" pe_min_bar="1" pe_max_bar="22" />
            <rotationModel idle_rotation_rate_invmin="700" max_rotation_rate_invmin="4500" dynamic_tyre_radius="0.31">
                <!-- gear box with 7 gears -->
                <gearRatio phi="16.7" />
                <gearRatio phi="10.1" />
                <gearRatio phi="6.8" />
                <gearRatio phi="5.0" />
                <gearRatio phi="3.8" />
                <gearRatio phi="3.1" />
                <gearRatio phi="2.6" />
            </rotationModel>
        </model>
    </consumption>
</movsim>
