=== AKAIsmael/movsim/sim/multiModelTrafficSimulatorInput.dtd
<?xml version="1.0" encoding="UTF-8"?> 

<!-- ##################################################################### -->
<!-- DTD Validation Grammar for multi model traffic simulator              -->
<!-- (c) 2011 Arne Kesting                                                 -->
<!-- ##################################################################### -->


<!-- ############################################################################## -->
<!-- Short reference for xml dtd syntax -->
<!-- http://www.herongyang.com/XML/DTD-Syntax-of-DTD-Statements.html -->
<!-- http://www.mihaiu.name/2005/xml-dtd-reference/ -->
<!-- <!ELEMENT> this tag is used to define an XML element type name and its permissible sub-elements;  -->
<!-- <!ELEMEMT elementName EMPTY>  : this element cannot have content, but it can have attributes -->
<!-- Element can have children but it cannot contain text (with the exception of whitespace): -->
<!-- <!ELEMENT elementName (child1, child2)> : element's children are specified using a sequence list thus they must appear in the specified order -->
<!-- <!ELEMENT elementName (child1 | child2)> : element's children are specified using a mutually exclusive choice list -->
<!-- Cardinality operators: ?="0 or 1"; *="0 to n";+="1 to n" -->
<!-- <!ATTLIST>  defines the attributes of an XML element (permissible and default values) -->
<!-- <!ATTLIST AnElement an_attribute CDATA #REQUIRED> : the attribute *must* be present in the XML document (is required) -->
<!-- <!ATTLIST AnElement an_attribute CDATA #IMPLIED> : the attribute is optional -->
<!-- <!ATTLIST AnElement an_attribute CDATA "value"> : attribute is optional and it has a default value; a validating parser will supply the default value if the attribute is not specified in the respective element -->
<!-- <!ATTLIST Test6 an_attribute (value1 | value2) #IMPLIED> : the attribute is optional but it can only have values from a predefined list -->
<!-- ############################################################################## -->
<!-- Here NMTOKEN is used for "normal" values, (true|false) indicate defined boolean values and CDATA is used when parsing allows also for constructs like "1/3.6" -->
<!-- ############################################################################## -->


<!-- general remarks: -->
<!-- all parameter values are expected in SI units. Otherwise the attribute's name is indicating the unit explicitely -->

<!ELEMENT SCENARIO (VEHICLES, SIMULATION) >

<!-- ##################################################################### -->
<!-- Vehicle-Driver-Units / Models                                         -->
<!-- ##################################################################### -->

<!ELEMENT VEHICLES (VEHICLE+) >

<!ELEMENT VEHICLE (LONGITUDINAL_MODEL, LANE_CHANGE_MODEL, MEMORY?, NOISE?) >

<!ATTLIST VEHICLE
  label           CDATA   #REQUIRED
  length          NMTOKEN #REQUIRED
  b_max           NMTOKEN "10000"
  reaction_time   NMTOKEN "0"
>

<!-- Longitudinal model elements -->
<!ELEMENT LONGITUDINAL_MODEL (IDM | ACC | OVM_VDIFF | GIPPS | NEWELL | NSM | KCA)>

<!-- see IDM paper and/or website for reference -->
<!ELEMENT IDM EMPTY>
<!ATTLIST IDM 
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  s1           NMTOKEN "0"
  T            NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  delta        NMTOKEN "4"
>

<!ELEMENT ACC EMPTY>
<!ATTLIST ACC
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  s1           NMTOKEN "0"
  T            NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  delta        NMTOKEN "4"
  coolness     NMTOKEN #REQUIRED
>


<!-- default: OVM variant with org. optimal velocity function -->
<!ELEMENT OVM_VDIFF EMPTY>
<!ATTLIST OVM_VDIFF
  v0          NMTOKEN #REQUIRED
  tau         NMTOKEN #REQUIRED
  s0          NMTOKEN #REQUIRED
  l_int       NMTOKEN #REQUIRED
  beta        NMTOKEN #REQUIRED
  lambda      NMTOKEN "0"
  variant     (0|1|2) "0"
>


<!ELEMENT GIPPS EMPTY>
<!ATTLIST GIPPS
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  dt           NMTOKEN #REQUIRED
>

<!-- TODO !! -->
<!ELEMENT NEWELL EMPTY>
<!ATTLIST NEWELL
>

<!ELEMENT NSM EMPTY>
<!ATTLIST NSM
v0           NMTOKEN #REQUIRED
p_slowdown   NMTOKEN #REQUIRED
p_slow_start NMTOKEN #REQUIRED
>

<!ELEMENT KCA EMPTY>
<!ATTLIST KCA
v0      NMTOKEN #REQUIRED
k       NMTOKEN #REQUIRED
pb0     NMTOKEN #REQUIRED
pb1     NMTOKEN #REQUIRED
pa1     NMTOKEN #REQUIRED
pa2     NMTOKEN #REQUIRED
vp      NMTOKEN #REQUIRED
>


<!-- no lane changing implemented so far (single lane simulator) -->
<!ELEMENT LANE_CHANGE_MODEL EMPTY>
<!ATTLIST LANE_CHANGE_MODEL 
>


<!-- Memory model, see paper for reference -->
<!ELEMENT MEMORY EMPTY>
<!ATTLIST MEMORY
tau     NMTOKEN #REQUIRED
alpha_T  NMTOKEN #REQUIRED
alpha_v0 NMTOKEN #REQUIRED
alpha_a  NMTOKEN "1"
>

<!-- Fluctuations:  -->
<!-- Wiener process (tau!=0) or delta-correlated white noise as alternatives -->
<!-- default is white noise -->
<!-- too strong fluctuations can provoke crashed -->
<!ELEMENT NOISE EMPTY>
<!ATTLIST NOISE
tau              NMTOKEN "0"
fluct_strength   NMTOKEN #REQUIRED 
>


<!-- ##################################################################### -->
<!-- Infrastructure and Simulation settings                                -->
<!-- ##################################################################### -->

<!ELEMENT SIMULATION (ROAD*)>
<!ATTLIST SIMULATION
  dt               NMTOKEN #REQUIRED
  duration            NMTOKEN #REQUIRED
  with_fixed_seed  (true|false)  "true" 
  seed             NMTOKEN "42"
> 

<!ELEMENT ROAD (TRAFFIC_COMPOSITION, INITIAL_CONDITIONS, TRAFFIC_SOURCE, TRAFFIC_SINK, FLOW_CONSERVING_INHOMOGENEITIES, SPEED_LIMITS, RAMPS, TRAFFIC_LIGHTS, OUTPUT)>

<!ATTLIST ROAD
  id               NMTOKEN #REQUIRED
  length            NMTOKEN #REQUIRED
  lanes            NMTOKEN "1"
> 


<!ELEMENT TRAFFIC_COMPOSITION (VEHICLE_TYPE+)>
<!ATTLIST TRAFFIC_COMPOSITION
  write_fund_diagrams  (false|true) "false"
>

<!ELEMENT VEHICLE_TYPE EMPTY >
<!ATTLIST VEHICLE_TYPE
  label     CDATA    #REQUIRED
  fraction  NMTOKEN  #REQUIRED
>

<!-- initial conditions (IC) -->

<!ELEMENT INITIAL_CONDITIONS (IC_MACRO*, IC_MICRO*)>
<!ATTLIST INITIAL_CONDITIONS 
> 

<!ELEMENT IC_MACRO EMPTY>
<!ATTLIST IC_MACRO
  x          NMTOKEN #REQUIRED
  rho_per_km NMTOKEN #REQUIRED
  v          NMTOKEN "0"
> 

<!-- most right lane is =1, increment for further lanes  -->
<!ELEMENT IC_MICRO EMPTY>
<!ATTLIST IC_MICRO
  x       NMTOKEN #REQUIRED
  v       NMTOKEN #REQUIRED
  lane    NMTOKEN "1"
  label   CDATA ""
> 

<!-- upstream boundary conditions -->
<!ELEMENT TRAFFIC_SOURCE (INFLOW*)>
<!ATTLIST TRAFFIC_SOURCE
with_logging  (true|false)  "false" 
>          

<!-- downstream boundary conditions (not yet implemented) -->
<!ELEMENT TRAFFIC_SINK EMPTY>
<!ATTLIST TRAFFIC_SINK
with_logging  (true|false) "false" 
>          


<!ELEMENT INFLOW EMPTY>
<!ATTLIST INFLOW
  t           NMTOKEN #REQUIRED
  q_per_hour  NMTOKEN #REQUIRED
  v           NMTOKEN "100"
> 



<!-- Flow-conserving inhomogeneities -->
<!ELEMENT FLOW_CONSERVING_INHOMOGENEITIES (INHOMOGENEITY*)>
<!ATTLIST FLOW_CONSERVING_INHOMOGENEITIES
> 

<!ELEMENT INHOMOGENEITY EMPTY>
<!ATTLIST INHOMOGENEITY
x         NMTOKEN #REQUIRED
alpha_T   NMTOKEN "1"
alpha_v0  NMTOKEN "1"
> 


<!-- speed limits -->
<!ELEMENT SPEED_LIMITS (SPEED_LIMIT*)>
<!ATTLIST SPEED_LIMITS
> 

<!ELEMENT SPEED_LIMIT EMPTY>
<!ATTLIST SPEED_LIMIT
x_init         NMTOKEN #REQUIRED
speedlimit_kmh NMTOKEN #REQUIRED
> 

  
<!-- ramps (onramps only) -->
<!ELEMENT RAMPS (SIMPLE_RAMP*, RAMP*)>
<!ATTLIST RAMPS
> 

<!ELEMENT SIMPLE_RAMP (INFLOW*)>
<!ATTLIST SIMPLE_RAMP
x_center       NMTOKEN #REQUIRED
length         NMTOKEN "1000"
with_logging  (true|false)  "false" 
> 


<!-- real physical ramp with merging area (length) and total length of x_max --> 
<!ELEMENT RAMP (INFLOW*)>
<!ATTLIST RAMP
x_center       NMTOKEN #REQUIRED
length         NMTOKEN "300"
x_max          NMTOKEN "1000"
with_logging  (true|false)  "false" 
> 
  
<!-- traffic lights -->
  
<!ELEMENT TRAFFIC_LIGHTS (TRAFFIC_LIGHT*)>
<!ATTLIST TRAFFIC_LIGHTS
> 
  
<!ELEMENT TRAFFIC_LIGHT EMPTY>
<!ATTLIST TRAFFIC_LIGHT
x                NMTOKEN #REQUIRED
green_time       NMTOKEN #REQUIRED
green_red_time   NMTOKEN #REQUIRED
red_time         NMTOKEN #REQUIRED
red_green_time   NMTOKEN #REQUIRED
phase_shift      NMTOKEN "0"
> 

<!-- ##################################################################### -->
<!--                           OUTPUT                                      -->
<!-- ##################################################################### -->

<!ELEMENT OUTPUT (SPATIOTEMPORAL?, FLOATING_CAR_DATA?, TRAJECTORIES?, DETECTORS?, TRAFFIC_LIGHT_RECORDER?) >

<!-- TODO ralph -->
<!ATTLIST OUTPUT
path CDATA "./"
>

<!-- output of spatio-temporal fields -->
<!ELEMENT SPATIOTEMPORAL EMPTY>
<!ATTLIST SPATIOTEMPORAL
  dt NMTOKEN "60"
  dx NMTOKEN "100"
>

<!-- possible output: percentage and/or dn and/or vla -->
<!ELEMENT FLOATING_CAR_DATA (FC*)>
<!ATTLIST FLOATING_CAR_DATA 
n_dt      NMTOKEN "1"
perc_out  NMTOKEN "0"
dn        NMTOKEN "0"
>

<!ELEMENT FC EMPTY>
<!ATTLIST FC
number  NMTOKEN #REQUIRED
>

<!-- <TRAJECTORIES dt_s="1" t_start_min="0" t_end_min="7" />  -->
<!ELEMENT TRAJECTORIES EMPTY>
<!ATTLIST TRAJECTORIES
  dt           NMTOKEN "1"
  t_start_min  NMTOKEN "0"
  t_end_min    NMTOKEN "1e10"
  x_start_km   NMTOKEN "0"
  x_end_km     NMTOKEN "1e10"
>


<!-- detectors can be placed with absolute and/or relative positions -->
<!ELEMENT DETECTORS  (CROSS_SECTION+) >
<!-- 1 min as default aggregation interval -->
<!ATTLIST DETECTORS
  dt  NMTOKEN "60" 
>

<!ELEMENT CROSS_SECTION EMPTY>
<!ATTLIST CROSS_SECTION 
  x  NMTOKEN #REQUIRED 
>



<!-- write time series of all traffic lights in one file  -->
<!ELEMENT TRAFFIC_LIGHT_RECORDER EMPTY>
<!ATTLIST TRAFFIC_LIGHT_RECORDER
  n_dt  NMTOKEN "1"
>

=== AKAIsmael/movsim/sim/games/ramp_metering_v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "multiModelTrafficSimulatorInput.dtd">
<!-- (c) Arne Kesting, Ralph Germ, Martin Budden, Martin Treiber (2012) -->
<SCENARIO network_filename="ramp_metering_v2.xodr">
    <VEHICLES>
        <VEHICLE label="ACC1" length="6" b_max="40">
            <LONGITUDINAL_MODEL>
                <ACC v0="35" T="1.2" s0="3" s1="2" delta="4" a="1.2" b="2.0" coolness="1"/>
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="true" crit_speed_eur="20">
                <!-- b_safe < b_max to avoid crashed -->
                <MOBIL b_safe="30.0" s_min="2.0" threshold="0.05" bias_right="0.1" politeness="0."/>
            </LANE_CHANGE_MODEL>
        </VEHICLE>
        <VEHICLE label="ACC2" length="6" b_max="40">
            <LONGITUDINAL_MODEL>
                <ACC v0="35" T="1.2" s0="3" s1="2" delta="4" a="1.2" b="2.0" coolness="1"/>
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="true" crit_speed_eur="20">
                <!-- b_safe < b_max to avoid crashed -->
                <MOBIL b_safe="30.0" s_min="2.0" threshold="0.05" bias_right="0.1" politeness="0."/>
            </LANE_CHANGE_MODEL>
        </VEHICLE>
        <VEHICLE label="Obstacle" length="0">
            <LONGITUDINAL_MODEL>
                <IDM v0="0" T="1" s0="2" a="1.0" b="1.5"/>
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL/>
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="0.2" duration="72000" fixed_seed="true" seed="42" crash_exit="false">
        <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="ACC1" fraction="1.0" relative_v0_randomization="0.0"/>
        </TRAFFIC_COMPOSITION>
        <ROAD id="1"> <!-- secondary road -->
            <TRAFFIC_COMPOSITION>
                <VEHICLE_TYPE label="ACC1" fraction="0.3" relative_v0_randomization="0.0" route_label="north"/>
                <VEHICLE_TYPE label="ACC2" fraction="0.7" relative_v0_randomization="0.0" route_label="north_then_east"/>
            </TRAFFIC_COMPOSITION>
            <INITIAL_CONDITIONS/>
            <TRAFFIC_SOURCE logging="false">
                <INFLOW t="0" q_per_hour="2000" v="24"/>
                <INFLOW t="60" q_per_hour="2000" v="24"/>
                <INFLOW t="150" q_per_hour="2000" v="24"/>
                <INFLOW t="210" q_per_hour="0" v="24"/>
           </TRAFFIC_SOURCE>
            <SPEED_LIMITS>
                <!--   <SPEED_LIMIT x="2600" speedlimit_kmh="80" /> -->
                <!--   <SPEED_LIMIT x="3600" speedlimit_kmh="200" /> -->
            </SPEED_LIMITS>
            <TRAFFIC_LIGHTS/>
            <DETECTORS/>
        </ROAD>
        <ROAD id="25"> <!-- freeway -->
            <INITIAL_CONDITIONS/>
            <TRAFFIC_SOURCE>
                <INFLOW t="0" q_per_hour="800" v="24"/>
                <INFLOW t="30" q_per_hour="1900" v="24"/>
                <INFLOW t="60" q_per_hour="2200" v="24"/>
                <INFLOW t="90" q_per_hour="1700" v="24"/>
                <INFLOW t="110" q_per_hour="2200" v="24"/>
                <INFLOW t="150" q_per_hour="2200" v="24"/>
                <INFLOW t="210" q_per_hour="0" v="24"/>
            </TRAFFIC_SOURCE>
            <SPEED_LIMITS/>
            <TRAFFIC_LIGHTS/>
            <DETECTORS/>
        </ROAD>
        <ROAD id="37">
            <INITIAL_CONDITIONS/>
            <TRAFFIC_LIGHTS>
                <!-- zero time period means that light will not change automatically from that color -->
                <!-- negative time period means that light will not use that color -->
                <TRAFFIC_LIGHT x="300" green_time="0" green_red_time="-1" red_time="0" red_green_time="-1" phase_shift="0"/>
            </TRAFFIC_LIGHTS>
        </ROAD>
        <ROUTES>
            <ROUTE label="north">
                <ROAD id="1" />
                <ROAD id="2" />
                <ROAD id="3" />
            </ROUTE>
            <ROUTE label="north_then_east">
                <ROAD id="1" />
                <ROAD id="2" />
                <ROAD id="37" />
                <ROAD id="26" />
                <ROAD id="27" />
            </ROUTE>
        </ROUTES>
        <OUTPUT/>
    </SIMULATION>
</SCENARIO>

=== AKAIsmael/movsim/sim/startStop_BARL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">
<!-- (c) Martin Treiber, Arne Kesting 2010 -->
<SCENARIO>
    <VEHICLES>
        <!-- vehicle length ==> cell units -->
        <VEHICLE label="BARL1" length="1">
            <!-- b_max not limited -->
            <LONGITUDINAL_MODEL>
                <!-- BARL variant : p0 != p possible -->
                <NSM v0="2" p_slowdown="0.1" p_slow_start="0.2" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
        <VEHICLE label="Obstacle" length="1">
            <!-- b_max not limited -->
            <LONGITUDINAL_MODEL>
                <NSM v0="0" p_slowdown="0" p_slow_start="0" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="1" duration="360" fixed_seed="true" seed="42">
        <ROAD id="1" length="20000" lanes="1">
            <TRAFFIC_COMPOSITION write_fund_diagrams="true">
                <VEHICLE_TYPE label="BARL1" fraction="1" />
                <VEHICLE_TYPE label="Obstacle" fraction="0" />
            </TRAFFIC_COMPOSITION>
            <INITIAL_CONDITIONS>
                <IC_MICRO x="1" v="0" label="BARL1" />
                <IC_MICRO x="2" v="0" label="BARL1" />
                <IC_MICRO x="3" v="0" label="BARL1" />
                <IC_MICRO x="4" v="0" label="BARL1" />
                <IC_MICRO x="5" v="0" label="BARL1" />
                <IC_MICRO x="6" v="0" label="BARL1" />
                <IC_MICRO x="7" v="0" label="BARL1" />
                <IC_MICRO x="8" v="0" label="BARL1" />
                <IC_MICRO x="9" v="0" label="BARL1" />
                <IC_MICRO x="10" v="0" label="BARL1" />
                <IC_MICRO x="11" v="0" label="BARL1" />
                <IC_MICRO x="12" v="0" label="BARL1" />
                <IC_MICRO x="13" v="0" label="BARL1" />
                <IC_MICRO x="14" v="0" label="BARL1" />
                <IC_MICRO x="15" v="0" label="BARL1" />
                <IC_MICRO x="16" v="0" label="BARL1" />
                <IC_MICRO x="17" v="0" label="BARL1" />
                <IC_MICRO x="18" v="0" label="BARL1" />
                <IC_MICRO x="19" v="0" label="BARL1" />
                <IC_MICRO x="20" v="0" label="BARL1" />
                <IC_MICRO x="21" v="0" label="BARL1" />
                <IC_MICRO x="22" v="0" label="BARL1" />
                <IC_MICRO x="23" v="0" label="BARL1" />
                <IC_MICRO x="24" v="0" label="BARL1" />
                <IC_MICRO x="25" v="0" label="BARL1" />
                <IC_MICRO x="26" v="0" label="BARL1" />
                <!-- obstacle shifts floating car numbers -->
                <IC_MICRO x="100" v="0" label="Obstacle" />
            </INITIAL_CONDITIONS>
            <TRAFFIC_SOURCE>
            </TRAFFIC_SOURCE>
            <TRAFFIC_SINK />
            <FLOW_CONSERVING_INHOMOGENEITIES>
            </FLOW_CONSERVING_INHOMOGENEITIES>
            <SPEED_LIMITS>
            </SPEED_LIMITS>
            <RAMPS>
            </RAMPS>
            <TRAFFIC_LIGHTS>
                <!-- not implemented for CA -->
            </TRAFFIC_LIGHTS>
            <DETECTORS />
            <OUTPUT>
                <FLOATING_CAR_DATA n_dt="1" perc_out="0" dn="0">
                    <!-- FC 1 is obstacle -->
                    <FC number="1" />
                    <FC number="2" />
                    <FC number="6" />
                    <FC number="11" />
                    <FC number="16" />
                    <FC number="21" />
                </FLOATING_CAR_DATA>
            </OUTPUT>
        </ROAD>
    </SIMULATION>
</SCENARIO>

=== AKAIsmael/movsim/sim/onramp_IDM_t.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">

<!-- (c) Martin Treiber, Arne Kesting 2011      -->

<SCENARIO>

<DRIVER_VEHICLE_UNITS>

  <VEHICLE label="IDM1" length="6" b_max="9"> 
    <LONGITUDINAL_MODEL>
       <IDM v0="33.33" T="1" s0="2" s1="0" delta="4" a="1.0" b="1.5" />
    </LONGITUDINAL_MODEL>
    <LANE_CHANGING_MODEL/>
  </VEHICLE>
</DRIVER_VEHICLE_UNITS>



<OUTPUT>
  <MACRO dx="100" dt="40"/>
  <DETECTORS dt="60"> 
    <CROSS_SECTION x="1000"/>
    <CROSS_SECTION x="6000"/>
    <CROSS_SECTION x="8000"/>
    <CROSS_SECTION x="9000"/>
    <CROSS_SECTION x="10000"/>
	<CROSS_SECTION x="11000"/>
    <CROSS_SECTION x="12000"/>
	<CROSS_SECTION x="13000"/>
    <CROSS_SECTION x="14000"/>
	<CROSS_SECTION x="15000"/>
	<CROSS_SECTION x="16000"/>
  </DETECTORS>
</OUTPUT>

<SIMULATION dt="0.4" x_max="20000" t_max="7200" lanes="1" with_fixed_seed="true" seed="42">

  <HETEROGENEITY write_fund_diagrams="true" >
    <VEHICLE_TYPE label="IDM1" fraction="1"  />
  </HETEROGENEITY>
  
  <INITIAL_CONDITIONS>
    <IC_MACRO x="8600" rho_invkm="2" v="30"/> 
  </INITIAL_CONDITIONS>

  <!-- auch noch qCap notwendig ?? -->
  <UPSTREAM_BOUNDARY_CONDITIONS with_logging="true" >
    <INFLOW t="0"     q_invh="200"   v="30" /> 
    <INFLOW t="1500"  q_invh="2200"  v="22" />
    <INFLOW t="10800" q_invh="1000"  v="30" /> 
  </UPSTREAM_BOUNDARY_CONDITIONS>

  <!-- improve veh performance at inflow -->
  <FLOW_CONSERVING_INHOMOGENEITIES>
   <INHOMOGENEITY x="0"     alpha_T="0.8"  /> 
   <INHOMOGENEITY x="2000" alpha_T="1"   />
  </FLOW_CONSERVING_INHOMOGENEITIES>
  

  <SPEED_LIMITS>
  </SPEED_LIMITS>

  <RAMPS>
    <RAMP x_center="15000" length="1000" with_logging="true" >
       <INFLOW t="0" q_invh="550" />
    </RAMP>
  </RAMPS>

  <TRAFFICLIGHTS>
  </TRAFFICLIGHTS>

</SIMULATION>

</SCENARIO>

=== AKAIsmael/movsim/viewer/src/main/resources/sim/offramp_onramp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">
<!-- (c) Martin Treiber, Arne Kesting 2011 -->
<SCENARIO path=".">
    <VEHICLES>
        <VEHICLE label="ACC1" length="8" b_max="9">
            <LONGITUDINAL_MODEL>
                <ACC v0="35" T="1.2" s0="2" s1="0" delta="4" a="1.2" b="2.0"
                    coolness="1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="true"
                crit_speed_eur="20">
                <MOBIL b_safe="5.0" s_min="2.0" threshold="0.1"
                    bias_right="0.05" politeness="0.1" />
            </LANE_CHANGE_MODEL>
        </VEHICLE>
        <!-- trucks -->
        <VEHICLE label="ACC2" length="16" b_max="9">
            <LONGITUDINAL_MODEL>
                <ACC v0="25" T="1.4" s0="2" s1="2" delta="4" a="0.8" b="2.0"
                    coolness="1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="true"
                crit_speed_eur="20">
                <MOBIL b_safe="4.0" s_min="2.0" threshold="0.2"
                    bias_right="0.3" politeness="0.1" />
            </LANE_CHANGE_MODEL>
        </VEHICLE>
        <VEHICLE label="Obstacle" length="0">
            <LONGITUDINAL_MODEL>
                <IDM v0="0" T="1" s0="2" a="1.0" b="1.5" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="0.2" duration="72000" fixed_seed="true" seed="42"
        crash_exit="false">
        <TRAFFIC_COMPOSITION write_fund_diagrams="false">
            <!-- <VEHICLE_TYPE label="IDM1" fraction="0" /> -->
            <VEHICLE_TYPE label="ACC1" fraction="0.8"
                relative_v0_randomization="0.2" />
            <VEHICLE_TYPE label="ACC2" fraction="0.2"
                relative_v0_randomization="0.2" />
        </TRAFFIC_COMPOSITION>
        <ROAD id="0" length="3800" lanes="2">
            <INITIAL_CONDITIONS>
                <IC_MACRO x="600" rho_per_km="2" v="30" />
            </INITIAL_CONDITIONS>
            <TRAFFIC_SOURCE logging="false">
                <INFLOW t="0" q_per_hour="1600" v="24" />
            </TRAFFIC_SOURCE>
            <TRAFFIC_SINK />
            <!-- improve vehicle performance at inflow -->
            <FLOW_CONSERVING_INHOMOGENEITIES>
                <INHOMOGENEITY x="0" alpha_T="0.7" />
                <INHOMOGENEITY x="1000" alpha_T="1" />
                <INHOMOGENEITY x="2500" alpha_T="1" />
                <INHOMOGENEITY x="2600" alpha_T="1.1" />
                <INHOMOGENEITY x="2700" alpha_T="1.0" />
            </FLOW_CONSERVING_INHOMOGENEITIES>
            <SPEED_LIMITS>
                <!-- <SPEED_LIMIT x="2600" speedlimit_kmh="80" /> -->
                <!-- <SPEED_LIMIT x="3600" speedlimit_kmh="200" /> -->
            </SPEED_LIMITS>
            <SIMPLE_RAMPS />
            <!-- length of offramp is calculated by used RoadMapping (here: RoadMappingPolyBezier) -->
            <TRAFFIC_LIGHTS />
            <DETECTORS />
        </ROAD>
        <ROAD id="-1" x="400" merge_length="300" length="2729.0">
            <INITIAL_CONDITIONS />
            <TRAFFIC_SOURCE id="0" />
            <TRAFFIC_SINK id="1" />
            <FLOW_CONSERVING_INHOMOGENEITIES />
            <SPEED_LIMITS>
                <SPEED_LIMIT x="600" speedlimit_kmh="50" />
                <SPEED_LIMIT x="2700" speedlimit_kmh="200" />
            </SPEED_LIMITS>
            <TRAFFIC_LIGHTS>
                <TRAFFIC_LIGHT x="2000" green_time="45"
                    green_red_time="3" red_time="30" red_green_time="2"
                    phase_shift="20" />
            </TRAFFIC_LIGHTS>
            <DETECTORS />
        </ROAD>


        <ROAD id="2" x="2500" merge_length="300" length="800">
            <INITIAL_CONDITIONS />
            <TRAFFIC_SOURCE logging="false">
                <INFLOW t="0" q_per_hour="450" />
            </TRAFFIC_SOURCE>
            <TRAFFIC_SINK id="0" />
            <FLOW_CONSERVING_INHOMOGENEITIES />
            <SPEED_LIMITS />
            <TRAFFIC_LIGHTS />
            <DETECTORS />
        </ROAD>
        <ROAD id="1" x="3200" merge_length="400" length="500">
            <INITIAL_CONDITIONS />
            <TRAFFIC_SOURCE id="-1" />
            <TRAFFIC_SINK id="0" />
            <FLOW_CONSERVING_INHOMOGENEITIES />
            <SPEED_LIMITS />
            <TRAFFIC_LIGHTS />
            <DETECTORS />
        </ROAD>
        <OUTPUT>
            <!-- <SPATIOTEMPORAL dx="100" dt="40" /> -->
            <!-- <TRAJECTORIES dt="1" start_time="0" end_time="420" start_x="2000" 
                end_x="5000" /> -->
            <TRAVELTIMES>
                <ROUTE start_id="0" start_pos="700" end_id="0" end_pos="3200" />
                <ROUTE start_id="-1" start_pos="300" end_id="1" end_pos="100" />
            </TRAVELTIMES>
        </OUTPUT>
    </SIMULATION>
</SCENARIO>

=== AKAIsmael/movsim/sim/offramp_onramp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">
<!-- (c) Martin Treiber, Arne Kesting 2011 -->
<SCENARIO path=".">
    <VEHICLES>
        <VEHICLE label="ACC1" length="6" b_max="9">
            <LONGITUDINAL_MODEL>
                <ACC v0="35" T="1.2" s0="2" s1="0" delta="4" a="1.2" b="2.0"
                    coolness="1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="true" crit_speed_eur="20">
                <MOBIL b_safe="4.0" s_min="2.0" threshold="0.2"
                    bias_right="0.1" politeness="0.1" />
            </LANE_CHANGE_MODEL>

        </VEHICLE>

        <!-- trucks -->
        <VEHICLE label="ACC2" length="16" b_max="9">
            <LONGITUDINAL_MODEL>
                <ACC v0="25" T="1.5" s0="4" s1="2" delta="4" a="0.8" b="1.5"
                    coolness="1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="true" crit_speed_eur="20">
                <MOBIL b_safe="4.0" s_min="2.0" threshold="0.2"
                    bias_right="0.3" politeness="0.2" />
            </LANE_CHANGE_MODEL>

        </VEHICLE>

       

        <VEHICLE label="Obstacle" length="0">
            <LONGITUDINAL_MODEL>
                <IDM v0="0" T="1" s0="2" a="1.0" b="1.5" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="0.2" duration="10000" fixed_seed="true" seed="42"
        crash_exit="true">
	<TRAFFIC_COMPOSITION write_fund_diagrams="false">
                <!-- <VEHICLE_TYPE label="IDM1" fraction="0" /> -->
                <VEHICLE_TYPE label="ACC1" fraction="0.8"
                    relative_v0_randomization="0.2" />
                <VEHICLE_TYPE label="ACC2" fraction="0.2"
                    relative_v0_randomization="0.2" />
        </TRAFFIC_COMPOSITION>
        <ROAD id="0" length="5000" lanes="2">
            <INITIAL_CONDITIONS>
                <IC_MACRO x="600" rho_per_km="2" v="30" />
            </INITIAL_CONDITIONS>
            <TRAFFIC_SOURCE logging="false">
                <INFLOW t="0" q_per_hour="22000" v="30" />
            </TRAFFIC_SOURCE>
            <TRAFFIC_SINK />
            <!-- improve vehicle performance at inflow -->
            <FLOW_CONSERVING_INHOMOGENEITIES>
                <INHOMOGENEITY x="0" alpha_T="0.7" />
                <INHOMOGENEITY x="1000" alpha_T="1" />
            </FLOW_CONSERVING_INHOMOGENEITIES>
            <SPEED_LIMITS>
              <!--   <SPEED_LIMIT x="2600" speedlimit_kmh="80" /> -->
              <!--   <SPEED_LIMIT x="3600" speedlimit_kmh="200" /> -->
            </SPEED_LIMITS>
          <RAMPS>
                <RAMP id="-1" x="1800" length="900" merge_length="400"
                    logging="false">
                    <TRAFFIC_SOURCE id="0" />
                    <TRAFFIC_SINK id="1" />
                </RAMP>
        	<RAMP id="2" x="3000" length="600" merge_length="400"
                    logging="false">
                    <TRAFFIC_SOURCE logging="false"> 
  		  <INFLOW t="0" q_per_hour="550" /> 
                   </TRAFFIC_SOURCE>    
                  <TRAFFIC_SINK id="0" />            
                  </RAMP>
               <RAMP id="1" x="4000" length="600" merge_length="400"
                    logging="false">
                    <TRAFFIC_SOURCE id="-1" />
                    <TRAFFIC_SINK id="0" />
                </RAMP>

               <!-- <RAMP id="1" x="3000" length="600" merge_length="400"
                    logging="false">
                    <TRAFFIC_SOURCE logging="false"> -->
                       <!-- <INFLOW t="0" q_per_hour="550" /> -->
                   <!-- </TRAFFIC_SOURCE>                </RAMP>-->

            </RAMPS>
            <TRAFFIC_LIGHTS>
            </TRAFFIC_LIGHTS>
            <DETECTORS />
        </ROAD>
        <OUTPUT>
            <!-- <SPATIOTEMPORAL dx="100" dt="40" /> -->
            <!-- <TRAJECTORIES dt="1" start_time="0" end_time="420" start_x="2000" 
                end_x="5000" /> -->
        </OUTPUT>
    </SIMULATION>
</SCENARIO>
