=== AKAIsmael/movsim/sim/multiModelTrafficSimulatorInput.dtd
<?xml version="1.0" encoding="UTF-8"?> 

<!-- ##################################################################### -->
<!-- DTD Validation Grammar for multi model traffic simulator              -->
<!-- (c) 2011 Arne Kesting                                                 -->
<!-- ##################################################################### -->


<!-- ############################################################################## -->
<!-- Short reference for xml dtd syntax -->
<!-- http://www.herongyang.com/XML/DTD-Syntax-of-DTD-Statements.html -->
<!-- http://www.mihaiu.name/2005/xml-dtd-reference/ -->
<!-- <!ELEMENT> this tag is used to define an XML element type name and its permissible sub-elements;  -->
<!-- <!ELEMEMT elementName EMPTY>  : this element cannot have content, but it can have attributes -->
<!-- Element can have children but it cannot contain text (with the exception of whitespace): -->
<!-- <!ELEMENT elementName (child1, child2)> : element's children are specified using a sequence list thus they must appear in the specified order -->
<!-- <!ELEMENT elementName (child1 | child2)> : element's children are specified using a mutually exclusive choice list -->
<!-- Cardinality operators: ?="0 or 1"; *="0 to n";+="1 to n" -->
<!-- <!ATTLIST>  defines the attributes of an XML element (permissible and default values) -->
<!-- <!ATTLIST AnElement an_attribute CDATA #REQUIRED> : the attribute *must* be present in the XML document (is required) -->
<!-- <!ATTLIST AnElement an_attribute CDATA #IMPLIED> : the attribute is optional -->
<!-- <!ATTLIST AnElement an_attribute CDATA "value"> : attribute is optional and it has a default value; a validating parser will supply the default value if the attribute is not specified in the respective element -->
<!-- <!ATTLIST Test6 an_attribute (value1 | value2) #IMPLIED> : the attribute is optional but it can only have values from a predefined list -->
<!-- ############################################################################## -->
<!-- Here NMTOKEN is used for "normal" values, (true|false) indicate defined boolean values and CDATA is used when parsing allows also for constructs like "1/3.6" -->
<!-- ############################################################################## -->


<!-- general remarks: -->
<!-- all parameter values are expected in SI units. Otherwise the attribute's name is indicating the unit explicitely -->

<!ELEMENT SCENARIO (VEHICLES, SIMULATION) >

<!-- ##################################################################### -->
<!-- Vehicle-Driver-Units / Models                                         -->
<!-- ##################################################################### -->

<!ELEMENT VEHICLES (VEHICLE+) >

<!ELEMENT VEHICLE (LONGITUDINAL_MODEL, LANE_CHANGE_MODEL, MEMORY?, NOISE?) >

<!ATTLIST VEHICLE
  label           CDATA   #REQUIRED
  length          NMTOKEN #REQUIRED
  b_max           NMTOKEN "10000"
  reaction_time   NMTOKEN "0"
>

<!-- Longitudinal model elements -->
<!ELEMENT LONGITUDINAL_MODEL (IDM | ACC | OVM_VDIFF | GIPPS | NEWELL | NSM | KCA)>

<!-- see IDM paper and/or website for reference -->
<!ELEMENT IDM EMPTY>
<!ATTLIST IDM 
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  s1           NMTOKEN "0"
  T            NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  delta        NMTOKEN "4"
>

<!ELEMENT ACC EMPTY>
<!ATTLIST ACC
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  s1           NMTOKEN "0"
  T            NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  delta        NMTOKEN "4"
  coolness     NMTOKEN #REQUIRED
>


<!-- default: OVM variant with org. optimal velocity function -->
<!ELEMENT OVM_VDIFF EMPTY>
<!ATTLIST OVM_VDIFF
  v0          NMTOKEN #REQUIRED
  tau         NMTOKEN #REQUIRED
  s0          NMTOKEN #REQUIRED
  l_int       NMTOKEN #REQUIRED
  beta        NMTOKEN #REQUIRED
  lambda      NMTOKEN "0"
  variant     (0|1|2) "0"
>


<!ELEMENT GIPPS EMPTY>
<!ATTLIST GIPPS
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  dt           NMTOKEN #REQUIRED
>

<!-- TODO !! -->
<!ELEMENT NEWELL EMPTY>
<!ATTLIST NEWELL
>

<!ELEMENT NSM EMPTY>
<!ATTLIST NSM
v0           NMTOKEN #REQUIRED
p_slowdown   NMTOKEN #REQUIRED
p_slow_start NMTOKEN #REQUIRED
>

<!ELEMENT KCA EMPTY>
<!ATTLIST KCA
v0      NMTOKEN #REQUIRED
k       NMTOKEN #REQUIRED
pb0     NMTOKEN #REQUIRED
pb1     NMTOKEN #REQUIRED
pa1     NMTOKEN #REQUIRED
pa2     NMTOKEN #REQUIRED
vp      NMTOKEN #REQUIRED
>


<!-- no lane changing implemented so far (single lane simulator) -->
<!ELEMENT LANE_CHANGE_MODEL EMPTY>
<!ATTLIST LANE_CHANGE_MODEL 
>


<!-- Memory model, see paper for reference -->
<!ELEMENT MEMORY EMPTY>
<!ATTLIST MEMORY
tau     NMTOKEN #REQUIRED
alpha_T  NMTOKEN #REQUIRED
alpha_v0 NMTOKEN #REQUIRED
alpha_a  NMTOKEN "1"
>

<!-- Fluctuations:  -->
<!-- Wiener process (tau!=0) or delta-correlated white noise as alternatives -->
<!-- default is white noise -->
<!-- too strong fluctuations can provoke crashed -->
<!ELEMENT NOISE EMPTY>
<!ATTLIST NOISE
tau              NMTOKEN "0"
fluct_strength   NMTOKEN #REQUIRED 
>


<!-- ##################################################################### -->
<!-- Infrastructure and Simulation settings                                -->
<!-- ##################################################################### -->

<!ELEMENT SIMULATION (ROAD*)>
<!ATTLIST SIMULATION
  dt               NMTOKEN #REQUIRED
  duration            NMTOKEN #REQUIRED
  with_fixed_seed  (true|false)  "true" 
  seed             NMTOKEN "42"
> 

<!ELEMENT ROAD (TRAFFIC_COMPOSITION, INITIAL_CONDITIONS, TRAFFIC_SOURCE, TRAFFIC_SINK, FLOW_CONSERVING_INHOMOGENEITIES, SPEED_LIMITS, RAMPS, TRAFFIC_LIGHTS, OUTPUT)>

<!ATTLIST ROAD
  id               NMTOKEN #REQUIRED
  length            NMTOKEN #REQUIRED
  lanes            NMTOKEN "1"
> 


<!ELEMENT TRAFFIC_COMPOSITION (VEHICLE_TYPE+)>
<!ATTLIST TRAFFIC_COMPOSITION
  write_fund_diagrams  (false|true) "false"
>

<!ELEMENT VEHICLE_TYPE EMPTY >
<!ATTLIST VEHICLE_TYPE
  label     CDATA    #REQUIRED
  fraction  NMTOKEN  #REQUIRED
>

<!-- initial conditions (IC) -->

<!ELEMENT INITIAL_CONDITIONS (IC_MACRO*, IC_MICRO*)>
<!ATTLIST INITIAL_CONDITIONS 
> 

<!ELEMENT IC_MACRO EMPTY>
<!ATTLIST IC_MACRO
  x          NMTOKEN #REQUIRED
  rho_per_km NMTOKEN #REQUIRED
  v          NMTOKEN "0"
> 

<!-- most right lane is =1, increment for further lanes  -->
<!ELEMENT IC_MICRO EMPTY>
<!ATTLIST IC_MICRO
  x       NMTOKEN #REQUIRED
  v       NMTOKEN #REQUIRED
  lane    NMTOKEN "1"
  label   CDATA ""
> 

<!-- upstream boundary conditions -->
<!ELEMENT TRAFFIC_SOURCE (INFLOW*)>
<!ATTLIST TRAFFIC_SOURCE
with_logging  (true|false)  "false" 
>          

<!-- downstream boundary conditions (not yet implemented) -->
<!ELEMENT TRAFFIC_SINK EMPTY>
<!ATTLIST TRAFFIC_SINK
with_logging  (true|false) "false" 
>          


<!ELEMENT INFLOW EMPTY>
<!ATTLIST INFLOW
  t           NMTOKEN #REQUIRED
  q_per_hour  NMTOKEN #REQUIRED
  v           NMTOKEN "100"
> 



<!-- Flow-conserving inhomogeneities -->
<!ELEMENT FLOW_CONSERVING_INHOMOGENEITIES (INHOMOGENEITY*)>
<!ATTLIST FLOW_CONSERVING_INHOMOGENEITIES
> 

<!ELEMENT INHOMOGENEITY EMPTY>
<!ATTLIST INHOMOGENEITY
x         NMTOKEN #REQUIRED
alpha_T   NMTOKEN "1"
alpha_v0  NMTOKEN "1"
> 


<!-- speed limits -->
<!ELEMENT SPEED_LIMITS (SPEED_LIMIT*)>
<!ATTLIST SPEED_LIMITS
> 

<!ELEMENT SPEED_LIMIT EMPTY>
<!ATTLIST SPEED_LIMIT
x_init         NMTOKEN #REQUIRED
speedlimit_kmh NMTOKEN #REQUIRED
> 

  
<!-- ramps (onramps only) -->
<!ELEMENT RAMPS (SIMPLE_RAMP*, RAMP*)>
<!ATTLIST RAMPS
> 

<!ELEMENT SIMPLE_RAMP (INFLOW*)>
<!ATTLIST SIMPLE_RAMP
x_center       NMTOKEN #REQUIRED
length         NMTOKEN "1000"
with_logging  (true|false)  "false" 
> 


<!-- real physical ramp with merging area (length) and total length of x_max --> 
<!ELEMENT RAMP (INFLOW*)>
<!ATTLIST RAMP
x_center       NMTOKEN #REQUIRED
length         NMTOKEN "300"
x_max          NMTOKEN "1000"
with_logging  (true|false)  "false" 
> 
  
<!-- traffic lights -->
  
<!ELEMENT TRAFFIC_LIGHTS (TRAFFIC_LIGHT*)>
<!ATTLIST TRAFFIC_LIGHTS
> 
  
<!ELEMENT TRAFFIC_LIGHT EMPTY>
<!ATTLIST TRAFFIC_LIGHT
x                NMTOKEN #REQUIRED
green_time       NMTOKEN #REQUIRED
green_red_time   NMTOKEN #REQUIRED
red_time         NMTOKEN #REQUIRED
red_green_time   NMTOKEN #REQUIRED
phase_shift      NMTOKEN "0"
> 

<!-- ##################################################################### -->
<!--                           OUTPUT                                      -->
<!-- ##################################################################### -->

<!ELEMENT OUTPUT (SPATIOTEMPORAL?, FLOATING_CAR_DATA?, TRAJECTORIES?, DETECTORS?, TRAFFIC_LIGHT_RECORDER?) >

<!-- TODO ralph -->
<!ATTLIST OUTPUT
path CDATA "./"
>

<!-- output of spatio-temporal fields -->
<!ELEMENT SPATIOTEMPORAL EMPTY>
<!ATTLIST SPATIOTEMPORAL
  dt NMTOKEN "60"
  dx NMTOKEN "100"
>

<!-- possible output: percentage and/or dn and/or vla -->
<!ELEMENT FLOATING_CAR_DATA (FC*)>
<!ATTLIST FLOATING_CAR_DATA 
n_dt      NMTOKEN "1"
perc_out  NMTOKEN "0"
dn        NMTOKEN "0"
>

<!ELEMENT FC EMPTY>
<!ATTLIST FC
number  NMTOKEN #REQUIRED
>

<!-- <TRAJECTORIES dt_s="1" t_start_min="0" t_end_min="7" />  -->
<!ELEMENT TRAJECTORIES EMPTY>
<!ATTLIST TRAJECTORIES
  dt           NMTOKEN "1"
  t_start_min  NMTOKEN "0"
  t_end_min    NMTOKEN "1e10"
  x_start_km   NMTOKEN "0"
  x_end_km     NMTOKEN "1e10"
>


<!-- detectors can be placed with absolute and/or relative positions -->
<!ELEMENT DETECTORS  (CROSS_SECTION+) >
<!-- 1 min as default aggregation interval -->
<!ATTLIST DETECTORS
  dt  NMTOKEN "60" 
>

<!ELEMENT CROSS_SECTION EMPTY>
<!ATTLIST CROSS_SECTION 
  x  NMTOKEN #REQUIRED 
>



<!-- write time series of all traffic lights in one file  -->
<!ELEMENT TRAFFIC_LIGHT_RECORDER EMPTY>
<!ATTLIST TRAFFIC_LIGHT_RECORDER
  n_dt  NMTOKEN "1"
>

=== AKAIsmael/movsim/src/main/resources/sim/startStop_VDIFF.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">
<!-- (c) Martin Treiber, Arne Kesting 2010      -->

<SCENARIO>

<DRIVER_VEHICLE_UNITS>

   <!-- variants: 0=fullVD orig, 1=fullVD secBased, 2=threePhase --> 
  <VEHICLE label="VDIFF1" length="8" b_max="20"> 
    <LONGITUDINAL_MODEL>
      <OVM_VDIFF v0="15" tau="5" s0="0" l_int="8" beta="1.5" lambda="0.6" variant="0"/>  
    </LONGITUDINAL_MODEL>
    <LANE_CHANGING_MODEL/>
  </VEHICLE>
	
</DRIVER_VEHICLE_UNITS>



<OUTPUT>
  <FLOATING_CAR_DATA  n_dt="5" perc_out="0" dn="0">
     <FC number="1" />
     <FC number="5" />
     <FC number="10" />
     <FC number="15" />
     <FC number="20" />
  </FLOATING_CAR_DATA>
</OUTPUT>

<SIMULATION dt="0.2" x_max="20000" t_max="360" lanes="1" with_fixed_seed="true" seed="42">
  <HETEROGENEITY write_fund_diagrams="true" >
    <VEHICLE_TYPE label="VDIFF1" fraction="1"  />
  </HETEROGENEITY>
  
  <INITIAL_CONDITIONS>
  <IC_MICRO x="10"  v="0" />  
  <IC_MICRO x="20"  v="0" />
  <IC_MICRO x="30"  v="0" />
  <IC_MICRO x="40"  v="0" />
  <IC_MICRO x="50"  v="0" />
  <IC_MICRO x="60"  v="0" />
  <IC_MICRO x="70"  v="0" />
  <IC_MICRO x="80"  v="0" />
  <IC_MICRO x="90"  v="0" />
  <IC_MICRO x="100" v="0" />
  <IC_MICRO x="110" v="0" />
  <IC_MICRO x="120" v="0" />
  <IC_MICRO x="130" v="0" />
  <IC_MICRO x="140" v="0" />
  <IC_MICRO x="150" v="0" />
  <IC_MICRO x="160" v="0" />
  <IC_MICRO x="170" v="0" />
  <IC_MICRO x="180" v="0" />
  <IC_MICRO x="190" v="0" />
  <IC_MICRO x="200" v="0" />
  <IC_MICRO x="210" v="0" />
  <IC_MICRO x="220" v="0" />
  <IC_MICRO x="230" v="0" />
  <IC_MICRO x="240" v="0" />
  <IC_MICRO x="250" v="0" />
  <IC_MICRO x="260" v="0" />
  </INITIAL_CONDITIONS>


  <UPSTREAM_BOUNDARY_CONDITIONS>
  </UPSTREAM_BOUNDARY_CONDITIONS>

  <FLOW_CONSERVING_INHOMOGENEITIES>
  </FLOW_CONSERVING_INHOMOGENEITIES>
  

  <SPEED_LIMITS>
  </SPEED_LIMITS>

  <RAMPS>
  </RAMPS>

  <TRAFFICLIGHTS>
    <TRAFFICLIGHT x="1000" green_time="30" green_red_time="3" red_time="400" red_green_time="2" phase_shift="0" />  
  </TRAFFICLIGHTS>

</SIMULATION>

</SCENARIO>

=== AKAIsmael/movsim/file/src/test/resources/movsim/benchOnramp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "multiModelTrafficSimulatorInput.dtd">
<SCENARIO>
	<VEHICLES>
		<VEHICLE label="IDM1" length="6" b_max="9">
			<LONGITUDINAL_MODEL>
				<IDM v0="33.33" T="1" s0="2" s1="0" delta="4" a="1.0" b="1.5"/>
			</LONGITUDINAL_MODEL>
			<LANE_CHANGE_MODEL/>
		</VEHICLE>
	</VEHICLES>
	<SIMULATION dt="0.5" duration="7200" seed="42">
		<ROAD id="1" length="20000" lanes="1">
			<TRAFFIC_COMPOSITION write_fund_diagrams="false">
				<VEHICLE_TYPE label="IDM1" fraction="1"/>
			</TRAFFIC_COMPOSITION>
			<INITIAL_CONDITIONS />
			<TRAFFIC_SOURCE logging="false">
				<INFLOW t="0" q_per_hour="2000" v="30"/>
			</TRAFFIC_SOURCE>
			<TRAFFIC_SINK />
			<FLOW_CONSERVING_INHOMOGENEITIES />
			<SPEED_LIMITS />
			<RAMPS>
				<RAMP x="15000" length="1000" logging="true">
					<INFLOW t="0" q_per_hour="500"/>
				</RAMP>
			</RAMPS>
			<TRAFFIC_LIGHTS />
			<OUTPUT>
				<SPATIOTEMPORAL dx="100" dt="60"/>
				<DETECTORS dt="60">
					<CROSS_SECTION x="1000"/>
					<CROSS_SECTION x="6000"/>
					<CROSS_SECTION x="8000"/>
					<CROSS_SECTION x="9000"/>
					<CROSS_SECTION x="10000"/>
					<CROSS_SECTION x="11000"/>
					<CROSS_SECTION x="12000"/>
					<CROSS_SECTION x="13000"/>
					<CROSS_SECTION x="14000"/>
					<CROSS_SECTION x="15000"/>
					<CROSS_SECTION x="16000"/>
				</DETECTORS>
			</OUTPUT>
		</ROAD>
	</SIMULATION>
</SCENARIO>

=== AKAIsmael/movsim/sim/onramp_IDM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">

<!-- (c) Martin Treiber, Arne Kesting 2011      -->

<SCENARIO>

<VEHICLES>

  <VEHICLE label="IDM1" length="6" b_max="9"> 
    <LONGITUDINAL_MODEL>
       <IDM v0="33.33" T="1" s0="2" s1="0" delta="4" a="1.0" b="1.5" />
    </LONGITUDINAL_MODEL>
    <LANE_CHANGE_MODEL/>
  </VEHICLE>
</VEHICLES>



<OUTPUT>
  <SPATIOTEMPORAL dx="100" dt="40"/>
  <TRAJECTORIES dt="1" t_start_min="0" t_end_min="7" x_start_km="2" x_end_km="5" />  
  <DETECTORS dt="60"> 
    <CROSS_SECTION x="1000"/>
    <CROSS_SECTION x="6000"/>
    <CROSS_SECTION x="8000"/>
    <CROSS_SECTION x="9000"/>
    <CROSS_SECTION x="10000"/>
	<CROSS_SECTION x="11000"/>
    <CROSS_SECTION x="12000"/>
	<CROSS_SECTION x="13000"/>
    <CROSS_SECTION x="14000"/>
	<CROSS_SECTION x="15000"/>
	<CROSS_SECTION x="16000"/>
  </DETECTORS>
</OUTPUT>

<SIMULATION dt="0.4" duration="7200" with_fixed_seed="true" seed="42">

  <ROAD id="1" length="20000" lanes="1" >
  <TRAFFIC_COMPOSITION write_fund_diagrams="true" >
    <VEHICLE_TYPE label="IDM1" fraction="1"  />
  </TRAFFIC_COMPOSITION>
  
  <INITIAL_CONDITIONS>
    <IC_MACRO x="8600" rho_invkm="2" v="30"/> 
  </INITIAL_CONDITIONS>

  <!-- auch noch qCap notwendig ?? -->
  <TRAFFIC_SOURCE with_logging="true" >
    <INFLOW t="0"     q_invh="200"   v="30" /> 
    <INFLOW t="1500"  q_invh="2200"  v="22" />
    <INFLOW t="10800" q_invh="1000"  v="30" /> 
  </TRAFFIC_SOURCE>
  
 
  <TRAFFIC_SINK />


  <!-- improve veh performance at inflow -->
  <FLOW_CONSERVING_INHOMOGENEITIES>
   <INHOMOGENEITY x="0"    alpha_T="0.8"  /> 
   <INHOMOGENEITY x="2000" alpha_T="1"   />
  </FLOW_CONSERVING_INHOMOGENEITIES>
  

  <SPEED_LIMITS>
  </SPEED_LIMITS>

  <RAMPS>
    <SIMPLE_RAMP x_center="15000" length="1000" with_logging="true" >
       <INFLOW t="0" q_invh="550" />
    </SIMPLE_RAMP>
  </RAMPS>

  <TRAFFIC_LIGHTS>
  </TRAFFIC_LIGHTS>
  
  
  </ROAD>
</SIMULATION>

</SCENARIO>

=== AKAIsmael/movsim/sim/onramp_multilane.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">
<!-- (c) Martin Treiber, Arne Kesting 2011 -->
<SCENARIO path=".">
    <VEHICLES>
        <VEHICLE label="IDM1" length="6" b_max="9">
            <LONGITUDINAL_MODEL>
                <IDM v0="33.33" T="1" s0="2" s1="0" delta="4" a="1.0" b="1.5" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="1" duration="7200" fixed_seed="true" seed="42">
        <ROAD id="1" length="2000" lanes="2">
            <TRAFFIC_COMPOSITION write_fund_diagrams="false">
                <VEHICLE_TYPE label="IDM1" fraction="1" />
            </TRAFFIC_COMPOSITION>
            <INITIAL_CONDITIONS>
                <IC_MACRO x="600" rho_per_km="2" v="30" />
            </INITIAL_CONDITIONS>
            <TRAFFIC_SOURCE logging="true">
                <INFLOW t="0" q_per_hour="200" v="30" />
                <INFLOW t="1500" q_per_hour="2200" v="22" />
                <INFLOW t="10800" q_per_hour="1000" v="30" />
            </TRAFFIC_SOURCE>
            <TRAFFIC_SINK />
            <!-- improve vehicle performance at inflow -->
            <FLOW_CONSERVING_INHOMOGENEITIES>
                <INHOMOGENEITY x="0" alpha_T="0.8" />
                <INHOMOGENEITY x="800" alpha_T="1" />
            </FLOW_CONSERVING_INHOMOGENEITIES>
            <SPEED_LIMITS>
            </SPEED_LIMITS>
            <RAMPS>
                <!-- <SIMPLE_RAMP x="1400" length="200" logging="false">
                    <INFLOW t="0" q_per_hour="550" />
                </SIMPLE_RAMP> -->
                <RAMP x="1400" length="200" x_max="1000" logging="true">
	          <TRAFFIC_SOURCE logging="true">
                     <INFLOW t="0" q_per_hour="500" />
                  </TRAFFIC_SOURCE>
                </RAMP>
            </RAMPS>
            <TRAFFIC_LIGHTS>
            </TRAFFIC_LIGHTS>
            <DETECTORS />
        </ROAD>
        <OUTPUT>
            <SPATIOTEMPORAL dx="100" dt="40" />
            <!-- <TRAJECTORIES dt="1" start_time="0" end_time="420" start_x="2000" 
                end_x="5000" /> -->
        </OUTPUT>
    </SIMULATION>
</SCENARIO>

=== AKAIsmael/movsim/sim/playground/ringroad_1lane_multi_models.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "multiModelTrafficSimulatorInput.dtd">

<!-- (c) Arne Kesting, Ralph Germ, Martin Budden, Martin Treiber (2012) -->
<!-- TODO: FCD Output does not work with macroscopic initial conditions -->
<SCENARIO network_filename="ringroad.xodr">
    <VEHICLES>
        <VEHICLE label="IDM" length="8" b_max="9">
            <LONGITUDINAL_MODEL>
                <IDM v0="20" T="1.2" s0="2" s1="0" delta="4" a="0.6" b="2.0" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
            <!-- fluctuation strength needed for traffic flow breakdown if simulating only with one vehicle type -->
            <NOISE tau="5" fluct_strength="0.07" />
        </VEHICLE>
         <VEHICLE label="IDMa" length="8" b_max="9">
            <LONGITUDINAL_MODEL>
                <IDM v0="20" T="1.2" s0="2" s1="0" delta="4" a="0.8" b="2.0" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
            <!-- fluctuation strength needed for traffic flow breakdown if simulating only with one vehicle type -->
            <NOISE tau="5" fluct_strength="0.07" />
        </VEHICLE>
         <VEHICLE label="KKW1" length="20">
            <LONGITUDINAL_MODEL>
                <KKW v0="28" k="2.55" pb0="0.425" pb1="0.04" pa1="0.2" pa2="0.052" vp="14" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
        <VEHICLE label="NSM1" length="1">
            <!-- b_max not limited -->
            <LONGITUDINAL_MODEL>
                <!-- BARL variant : p0 != p possible -->
                <NSM v0="2" p_slowdown="0.1" p_slow_start="0.1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="1" duration="100000" fixed_seed="true" seed="42">
          <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="IDM" fraction="1" />
            <VEHICLE_TYPE label="IDMa" fraction="1" />
            <VEHICLE_TYPE label="KKW1" fraction="1" />
            <VEHICLE_TYPE label="NSM1" fraction="1" />
        </TRAFFIC_COMPOSITION>
        <ROAD id="1">
          <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="IDM" fraction="1" />
        </TRAFFIC_COMPOSITION>
            <INITIAL_CONDITIONS>
                <!-- critical density for emerging stop-and-go wave about >= 33 vehicles per km per lane -->
                <IC_MACRO x="1" rho_per_km="36" v="20" />
            </INITIAL_CONDITIONS>
        </ROAD>
         <ROAD id="3">
           <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="KKW1" fraction="1" />
        </TRAFFIC_COMPOSITION>
            <INITIAL_CONDITIONS>
                <IC_MACRO x="1" rho_per_km="36" v="20" />
            </INITIAL_CONDITIONS>
        </ROAD>
          <ROAD id="2">
           <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="NSM1" fraction="1" />
        </TRAFFIC_COMPOSITION>
            <INITIAL_CONDITIONS>
                <IC_MACRO x="1" rho_per_km="36" v="20" />
            </INITIAL_CONDITIONS>
        </ROAD>
        <OUTPUT>
        </OUTPUT>
    </SIMULATION>
</SCENARIO>

=== AKAIsmael/movsim/sim/bookScenarioStartStop/startStop_all_iteratedmaps.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "multiModelTrafficSimulatorInput.dtd">

<!-- (c) Movsim, Arne Kesting 2012 -->
<SCENARIO network_filename="startStop_all_iteratedmaps.xodr">
    <VEHICLES write_fund_diagrams="false">
    <VEHICLE label="GIPPS1" length="8" b_max="20">
            <LONGITUDINAL_MODEL>
                <GIPPS v0="15" a="1.5" b="1.0" s0="2" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
        <VEHICLE label="KRAUSS1" length="8" b_max="20">
            <LONGITUDINAL_MODEL>
                <KRAUSS v0="15" a="1.0" b="1.0" s0="2" epsilon="0.4" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
        <VEHICLE label="NEWELL1" length="8" b_max="9">
            <LONGITUDINAL_MODEL>
                <NEWELL v0="15" s0="2" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
        <VEHICLE label="Obstacle" length="8" b_max="20">
            <LONGITUDINAL_MODEL>
                <GIPPS v0="0" a="1.5" b="1.0" s0="2" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="0.2" duration="360" fixed_seed="true" seed="42" crash_exit="false">
        <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="GIPPS1" fraction="1" />
        </TRAFFIC_COMPOSITION>
                <!-- ############################ -->
        <ROAD id="GIPPS">
          <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="GIPPS1" fraction="1" />
           <VEHICLE_TYPE label="Obstacle" fraction="0" /> 
        </TRAFFIC_COMPOSITION>
            <INITIAL_CONDITIONS>
                <IC_MICRO x="10" v="0" />
                <IC_MICRO x="20" v="0" />
                <IC_MICRO x="30" v="0" />
                <IC_MICRO x="40" v="0" />
                <IC_MICRO x="50" v="0" />
                <IC_MICRO x="60" v="0" />
                <IC_MICRO x="70" v="0" />
                <IC_MICRO x="80" v="0" />
                <IC_MICRO x="90" v="0" />
                <IC_MICRO x="100" v="0" />
                <IC_MICRO x="110" v="0" />
                <IC_MICRO x="120" v="0" />
                <IC_MICRO x="130" v="0" />
                <IC_MICRO x="140" v="0" />
                <IC_MICRO x="150" v="0" />
                <IC_MICRO x="160" v="0" />
                <IC_MICRO x="170" v="0" />
                <IC_MICRO x="180" v="0" />
                <IC_MICRO x="190" v="0" />
                <IC_MICRO x="200" v="0" />
                <IC_MICRO x="210" v="0" />
                <IC_MICRO x="220" v="0" />
                <IC_MICRO x="230" v="0" />
                <IC_MICRO x="240" v="0" />
                <IC_MICRO x="250" v="0" />
                <IC_MICRO x="260" v="0" />
                <!-- obstacle shifts floating car numbers -->
                <IC_MICRO x="2000" v="0" label="Obstacle" />
            </INITIAL_CONDITIONS>
                 </ROAD>
                                 <!-- ############################ -->
                         <ROAD id="KRAUSS">
                          <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="KRAUSS1" fraction="1" />
           <VEHICLE_TYPE label="Obstacle" fraction="0" /> 
        </TRAFFIC_COMPOSITION>
                          <INITIAL_CONDITIONS>
                <IC_MICRO x="10" v="0" />
                <IC_MICRO x="20" v="0" />
                <IC_MICRO x="30" v="0" />
                <IC_MICRO x="40" v="0" />
                <IC_MICRO x="50" v="0" />
                <IC_MICRO x="60" v="0" />
                <IC_MICRO x="70" v="0" />
                <IC_MICRO x="80" v="0" />
                <IC_MICRO x="90" v="0" />
                <IC_MICRO x="100" v="0" />
                <IC_MICRO x="110" v="0" />
                <IC_MICRO x="120" v="0" />
                <IC_MICRO x="130" v="0" />
                <IC_MICRO x="140" v="0" />
                <IC_MICRO x="150" v="0" />
                <IC_MICRO x="160" v="0" />
                <IC_MICRO x="170" v="0" />
                <IC_MICRO x="180" v="0" />
                <IC_MICRO x="190" v="0" />
                <IC_MICRO x="200" v="0" />
                <IC_MICRO x="210" v="0" />
                <IC_MICRO x="220" v="0" />
                <IC_MICRO x="230" v="0" />
                <IC_MICRO x="240" v="0" />
                <IC_MICRO x="250" v="0" />
                <IC_MICRO x="260" v="0" />
                <!-- obstacle shifts floating car numbers -->
                <IC_MICRO x="2000" v="0" label="Obstacle" />
            </INITIAL_CONDITIONS>
                 </ROAD>
                 
                 
            
        <ROAD id="NEWELL">
               <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="NEWELL1" fraction="1" />
            <VEHICLE_TYPE label="Obstacle" fraction="0" />
        </TRAFFIC_COMPOSITION>
            <INITIAL_CONDITIONS>
                <IC_MICRO x="10" v="0" />
                <IC_MICRO x="20" v="0" />
                <IC_MICRO x="30" v="0" />
                <IC_MICRO x="40" v="0" />
                <IC_MICRO x="50" v="0" />
                <IC_MICRO x="60" v="0" />
                <IC_MICRO x="70" v="0" />
                <IC_MICRO x="80" v="0" />
                <IC_MICRO x="90" v="0" />
                <IC_MICRO x="100" v="0" />
                <IC_MICRO x="110" v="0" />
                <IC_MICRO x="120" v="0" />
                <IC_MICRO x="130" v="0" />
                <IC_MICRO x="140" v="0" />
                <IC_MICRO x="150" v="0" />
                <IC_MICRO x="160" v="0" />
                <IC_MICRO x="170" v="0" />
                <IC_MICRO x="180" v="0" />
                <IC_MICRO x="190" v="0" />
                <IC_MICRO x="200" v="0" />
                <IC_MICRO x="210" v="0" />
                <IC_MICRO x="220" v="0" />
                <IC_MICRO x="230" v="0" />
                <IC_MICRO x="240" v="0" />
                <IC_MICRO x="250" v="0" />
                <IC_MICRO x="260" v="0" />
                <!-- obstacle shifts floating car numbers -->
                <IC_MICRO x="2000" v="0" label="Obstacle" />
            </INITIAL_CONDITIONS>
        </ROAD>
        <OUTPUT />
    </SIMULATION>
</SCENARIO>
