=== AKAIsmael/movsim/sim/multiModelTrafficSimulatorInput.dtd
<?xml version="1.0" encoding="UTF-8"?> 

<!-- ##################################################################### -->
<!-- DTD Validation Grammar for multi model traffic simulator              -->
<!-- (c) 2011 Arne Kesting                                                 -->
<!-- ##################################################################### -->


<!-- ############################################################################## -->
<!-- Short reference for xml dtd syntax -->
<!-- http://www.herongyang.com/XML/DTD-Syntax-of-DTD-Statements.html -->
<!-- http://www.mihaiu.name/2005/xml-dtd-reference/ -->
<!-- <!ELEMENT> this tag is used to define an XML element type name and its permissible sub-elements;  -->
<!-- <!ELEMEMT elementName EMPTY>  : this element cannot have content, but it can have attributes -->
<!-- Element can have children but it cannot contain text (with the exception of whitespace): -->
<!-- <!ELEMENT elementName (child1, child2)> : element's children are specified using a sequence list thus they must appear in the specified order -->
<!-- <!ELEMENT elementName (child1 | child2)> : element's children are specified using a mutually exclusive choice list -->
<!-- Cardinality operators: ?="0 or 1"; *="0 to n";+="1 to n" -->
<!-- <!ATTLIST>  defines the attributes of an XML element (permissible and default values) -->
<!-- <!ATTLIST AnElement an_attribute CDATA #REQUIRED> : the attribute *must* be present in the XML document (is required) -->
<!-- <!ATTLIST AnElement an_attribute CDATA #IMPLIED> : the attribute is optional -->
<!-- <!ATTLIST AnElement an_attribute CDATA "value"> : attribute is optional and it has a default value; a validating parser will supply the default value if the attribute is not specified in the respective element -->
<!-- <!ATTLIST Test6 an_attribute (value1 | value2) #IMPLIED> : the attribute is optional but it can only have values from a predefined list -->
<!-- ############################################################################## -->
<!-- Here NMTOKEN is used for "normal" values, (true|false) indicate defined boolean values and CDATA is used when parsing allows also for constructs like "1/3.6" -->
<!-- ############################################################################## -->


<!-- general remarks: -->
<!-- all parameter values are expected in SI units. Otherwise the attribute's name is indicating the unit explicitely -->

<!ELEMENT SCENARIO (VEHICLES, SIMULATION) >

<!-- ##################################################################### -->
<!-- Vehicle-Driver-Units / Models                                         -->
<!-- ##################################################################### -->

<!ELEMENT VEHICLES (VEHICLE+) >

<!ELEMENT VEHICLE (LONGITUDINAL_MODEL, LANE_CHANGE_MODEL, MEMORY?, NOISE?) >

<!ATTLIST VEHICLE
  label           CDATA   #REQUIRED
  length          NMTOKEN #REQUIRED
  b_max           NMTOKEN "10000"
  reaction_time   NMTOKEN "0"
>

<!-- Longitudinal model elements -->
<!ELEMENT LONGITUDINAL_MODEL (IDM | ACC | OVM_VDIFF | GIPPS | NEWELL | NSM | KCA)>

<!-- see IDM paper and/or website for reference -->
<!ELEMENT IDM EMPTY>
<!ATTLIST IDM 
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  s1           NMTOKEN "0"
  T            NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  delta        NMTOKEN "4"
>

<!ELEMENT ACC EMPTY>
<!ATTLIST ACC
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  s1           NMTOKEN "0"
  T            NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  delta        NMTOKEN "4"
  coolness     NMTOKEN #REQUIRED
>


<!-- default: OVM variant with org. optimal velocity function -->
<!ELEMENT OVM_VDIFF EMPTY>
<!ATTLIST OVM_VDIFF
  v0          NMTOKEN #REQUIRED
  tau         NMTOKEN #REQUIRED
  s0          NMTOKEN #REQUIRED
  l_int       NMTOKEN #REQUIRED
  beta        NMTOKEN #REQUIRED
  lambda      NMTOKEN "0"
  variant     (0|1|2) "0"
>


<!ELEMENT GIPPS EMPTY>
<!ATTLIST GIPPS
  v0           NMTOKEN #REQUIRED
  s0           NMTOKEN #REQUIRED
  a            NMTOKEN #REQUIRED
  b            NMTOKEN #REQUIRED
  dt           NMTOKEN #REQUIRED
>

<!-- TODO !! -->
<!ELEMENT NEWELL EMPTY>
<!ATTLIST NEWELL
>

<!ELEMENT NSM EMPTY>
<!ATTLIST NSM
v0           NMTOKEN #REQUIRED
p_slowdown   NMTOKEN #REQUIRED
p_slow_start NMTOKEN #REQUIRED
>

<!ELEMENT KCA EMPTY>
<!ATTLIST KCA
v0      NMTOKEN #REQUIRED
k       NMTOKEN #REQUIRED
pb0     NMTOKEN #REQUIRED
pb1     NMTOKEN #REQUIRED
pa1     NMTOKEN #REQUIRED
pa2     NMTOKEN #REQUIRED
vp      NMTOKEN #REQUIRED
>


<!-- no lane changing implemented so far (single lane simulator) -->
<!ELEMENT LANE_CHANGE_MODEL EMPTY>
<!ATTLIST LANE_CHANGE_MODEL 
>


<!-- Memory model, see paper for reference -->
<!ELEMENT MEMORY EMPTY>
<!ATTLIST MEMORY
tau     NMTOKEN #REQUIRED
alpha_T  NMTOKEN #REQUIRED
alpha_v0 NMTOKEN #REQUIRED
alpha_a  NMTOKEN "1"
>

<!-- Fluctuations:  -->
<!-- Wiener process (tau!=0) or delta-correlated white noise as alternatives -->
<!-- default is white noise -->
<!-- too strong fluctuations can provoke crashed -->
<!ELEMENT NOISE EMPTY>
<!ATTLIST NOISE
tau              NMTOKEN "0"
fluct_strength   NMTOKEN #REQUIRED 
>


<!-- ##################################################################### -->
<!-- Infrastructure and Simulation settings                                -->
<!-- ##################################################################### -->

<!ELEMENT SIMULATION (ROAD*)>
<!ATTLIST SIMULATION
  dt               NMTOKEN #REQUIRED
  duration            NMTOKEN #REQUIRED
  with_fixed_seed  (true|false)  "true" 
  seed             NMTOKEN "42"
> 

<!ELEMENT ROAD (TRAFFIC_COMPOSITION, INITIAL_CONDITIONS, TRAFFIC_SOURCE, TRAFFIC_SINK, FLOW_CONSERVING_INHOMOGENEITIES, SPEED_LIMITS, RAMPS, TRAFFIC_LIGHTS, OUTPUT)>

<!ATTLIST ROAD
  id               NMTOKEN #REQUIRED
  length            NMTOKEN #REQUIRED
  lanes            NMTOKEN "1"
> 


<!ELEMENT TRAFFIC_COMPOSITION (VEHICLE_TYPE+)>
<!ATTLIST TRAFFIC_COMPOSITION
  write_fund_diagrams  (false|true) "false"
>

<!ELEMENT VEHICLE_TYPE EMPTY >
<!ATTLIST VEHICLE_TYPE
  label     CDATA    #REQUIRED
  fraction  NMTOKEN  #REQUIRED
>

<!-- initial conditions (IC) -->

<!ELEMENT INITIAL_CONDITIONS (IC_MACRO*, IC_MICRO*)>
<!ATTLIST INITIAL_CONDITIONS 
> 

<!ELEMENT IC_MACRO EMPTY>
<!ATTLIST IC_MACRO
  x          NMTOKEN #REQUIRED
  rho_per_km NMTOKEN #REQUIRED
  v          NMTOKEN "0"
> 

<!-- most right lane is =1, increment for further lanes  -->
<!ELEMENT IC_MICRO EMPTY>
<!ATTLIST IC_MICRO
  x       NMTOKEN #REQUIRED
  v       NMTOKEN #REQUIRED
  lane    NMTOKEN "1"
  label   CDATA ""
> 

<!-- upstream boundary conditions -->
<!ELEMENT TRAFFIC_SOURCE (INFLOW*)>
<!ATTLIST TRAFFIC_SOURCE
with_logging  (true|false)  "false" 
>          

<!-- downstream boundary conditions (not yet implemented) -->
<!ELEMENT TRAFFIC_SINK EMPTY>
<!ATTLIST TRAFFIC_SINK
with_logging  (true|false) "false" 
>          


<!ELEMENT INFLOW EMPTY>
<!ATTLIST INFLOW
  t           NMTOKEN #REQUIRED
  q_per_hour  NMTOKEN #REQUIRED
  v           NMTOKEN "100"
> 



<!-- Flow-conserving inhomogeneities -->
<!ELEMENT FLOW_CONSERVING_INHOMOGENEITIES (INHOMOGENEITY*)>
<!ATTLIST FLOW_CONSERVING_INHOMOGENEITIES
> 

<!ELEMENT INHOMOGENEITY EMPTY>
<!ATTLIST INHOMOGENEITY
x         NMTOKEN #REQUIRED
alpha_T   NMTOKEN "1"
alpha_v0  NMTOKEN "1"
> 


<!-- speed limits -->
<!ELEMENT SPEED_LIMITS (SPEED_LIMIT*)>
<!ATTLIST SPEED_LIMITS
> 

<!ELEMENT SPEED_LIMIT EMPTY>
<!ATTLIST SPEED_LIMIT
x_init         NMTOKEN #REQUIRED
speedlimit_kmh NMTOKEN #REQUIRED
> 

  
<!-- ramps (onramps only) -->
<!ELEMENT RAMPS (SIMPLE_RAMP*, RAMP*)>
<!ATTLIST RAMPS
> 

<!ELEMENT SIMPLE_RAMP (INFLOW*)>
<!ATTLIST SIMPLE_RAMP
x_center       NMTOKEN #REQUIRED
length         NMTOKEN "1000"
with_logging  (true|false)  "false" 
> 


<!-- real physical ramp with merging area (length) and total length of x_max --> 
<!ELEMENT RAMP (INFLOW*)>
<!ATTLIST RAMP
x_center       NMTOKEN #REQUIRED
length         NMTOKEN "300"
x_max          NMTOKEN "1000"
with_logging  (true|false)  "false" 
> 
  
<!-- traffic lights -->
  
<!ELEMENT TRAFFIC_LIGHTS (TRAFFIC_LIGHT*)>
<!ATTLIST TRAFFIC_LIGHTS
> 
  
<!ELEMENT TRAFFIC_LIGHT EMPTY>
<!ATTLIST TRAFFIC_LIGHT
x                NMTOKEN #REQUIRED
green_time       NMTOKEN #REQUIRED
green_red_time   NMTOKEN #REQUIRED
red_time         NMTOKEN #REQUIRED
red_green_time   NMTOKEN #REQUIRED
phase_shift      NMTOKEN "0"
> 

<!-- ##################################################################### -->
<!--                           OUTPUT                                      -->
<!-- ##################################################################### -->

<!ELEMENT OUTPUT (SPATIOTEMPORAL?, FLOATING_CAR_DATA?, TRAJECTORIES?, DETECTORS?, TRAFFIC_LIGHT_RECORDER?) >

<!-- TODO ralph -->
<!ATTLIST OUTPUT
path CDATA "./"
>

<!-- output of spatio-temporal fields -->
<!ELEMENT SPATIOTEMPORAL EMPTY>
<!ATTLIST SPATIOTEMPORAL
  dt NMTOKEN "60"
  dx NMTOKEN "100"
>

<!-- possible output: percentage and/or dn and/or vla -->
<!ELEMENT FLOATING_CAR_DATA (FC*)>
<!ATTLIST FLOATING_CAR_DATA 
n_dt      NMTOKEN "1"
perc_out  NMTOKEN "0"
dn        NMTOKEN "0"
>

<!ELEMENT FC EMPTY>
<!ATTLIST FC
number  NMTOKEN #REQUIRED
>

<!-- <TRAJECTORIES dt_s="1" t_start_min="0" t_end_min="7" />  -->
<!ELEMENT TRAJECTORIES EMPTY>
<!ATTLIST TRAJECTORIES
  dt           NMTOKEN "1"
  t_start_min  NMTOKEN "0"
  t_end_min    NMTOKEN "1e10"
  x_start_km   NMTOKEN "0"
  x_end_km     NMTOKEN "1e10"
>


<!-- detectors can be placed with absolute and/or relative positions -->
<!ELEMENT DETECTORS  (CROSS_SECTION+) >
<!-- 1 min as default aggregation interval -->
<!ATTLIST DETECTORS
  dt  NMTOKEN "60" 
>

<!ELEMENT CROSS_SECTION EMPTY>
<!ATTLIST CROSS_SECTION 
  x  NMTOKEN #REQUIRED 
>



<!-- write time series of all traffic lights in one file  -->
<!ELEMENT TRAFFIC_LIGHT_RECORDER EMPTY>
<!ATTLIST TRAFFIC_LIGHT_RECORDER
  n_dt  NMTOKEN "1"
>

=== AKAIsmael/movsim/src/main/resources/sim/test_trafficlights_IDM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">


<!-- (c) Martin Treiber, Arne Kesting 2010      -->

<SCENARIO>

<DRIVER_VEHICLE_UNITS>

  <VEHICLE label="IDM1" length="8" b_max="9"> 
    <LONGITUDINAL_MODEL>
       <IDM v0="25" T="1" s0="2" s1="0" delta="4" a="1.0" b="1.5" />
    </LONGITUDINAL_MODEL>
    <LANE_CHANGING_MODEL/>
  </VEHICLE>
</DRIVER_VEHICLE_UNITS>



<OUTPUT>
  <FLOATING_CAR_DATA n_dt="5" perc_out="0" dn="0">
     <FC number="1" />
     <FC number="4" />
     <FC number="8" />
     <FC number="12" />
     <FC number="16" />
     <FC number="20" />
     <FC number="24" />
	 <FC number="28" />
	 <FC number="32" />
	 <FC number="36" />
	 <FC number="40" />

  </FLOATING_CAR_DATA>
  <TRAFFICLIGHT_RECORDER n_dt="5"  /> <!-- for testing -->
</OUTPUT>

<SIMULATION dt="0.2" x_max="1500" t_max="400" lanes="1" with_fixed_seed="true" seed="42">

  <HETEROGENEITY write_fund_diagrams="true" >
    <VEHICLE_TYPE label="IDM1" fraction="1"  />
  </HETEROGENEITY>
  
  <INITIAL_CONDITIONS>
   <IC_MICRO x="10"  v="0" />  
  <IC_MICRO x="20"  v="0" />
  <IC_MICRO x="30"  v="0" />
  <IC_MICRO x="40"  v="0" />
  <IC_MICRO x="50"  v="0" />
  <IC_MICRO x="60"  v="0" />
  <IC_MICRO x="70"  v="0" />
  <IC_MICRO x="80"  v="0" />
  <IC_MICRO x="90"  v="0" />
  <IC_MICRO x="100" v="0" />
  <IC_MICRO x="110" v="0" />
  <IC_MICRO x="120" v="0" />
  <IC_MICRO x="130" v="0" />
  <IC_MICRO x="140" v="0" />
  <IC_MICRO x="150" v="0" />
  <IC_MICRO x="160" v="0" />
  <IC_MICRO x="170" v="0" />
  <IC_MICRO x="180" v="0" />
  <IC_MICRO x="190" v="0" />
  <IC_MICRO x="200" v="0" />
  <IC_MICRO x="220" v="0" />
  <IC_MICRO x="240" v="0" />
  <IC_MICRO x="260" v="0" />
  </INITIAL_CONDITIONS>


  <UPSTREAM_BOUNDARY_CONDITIONS>
    <INFLOW t="0"  q_invh="300"   v="30" />
  </UPSTREAM_BOUNDARY_CONDITIONS>

  <FLOW_CONSERVING_INHOMOGENEITIES>
  </FLOW_CONSERVING_INHOMOGENEITIES>
  

  <SPEED_LIMITS>
  </SPEED_LIMITS>

  <RAMPS>
  </RAMPS>

  <TRAFFICLIGHTS>
     <TRAFFICLIGHT x="700" green_time="30" green_red_time="3" red_time="45" red_green_time="2" phase_shift="0" /> 
	 <TRAFFICLIGHT x="1200" green_time="15" green_red_time="3" red_time="45" red_green_time="2" phase_shift="10" /> 
  </TRAFFICLIGHTS>

</SIMULATION>

</SCENARIO>

=== AKAIsmael/movsim/sim/startStop_OVM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">
<!-- (c) Martin Treiber, Arne Kesting 2010 -->
<SCENARIO>
    <VEHICLES>
        <VEHICLE label="OVM1" length="8" b_max="20">
            <LONGITUDINAL_MODEL>
                <OVM_VDIFF v0="15" tau="0.65" s0="0 " l_int="8" beta="1.5"
                    lambda="0" variant="0" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="0.2" duration="360" with_fixed_seed="true" seed="42">
        <ROAD id="1" length="20000" lanes="1">
            <TRAFFIC_COMPOSITION write_fund_diagrams="true">
                <VEHICLE_TYPE label="OVM1" fraction="1" />
            </TRAFFIC_COMPOSITION>
            <INITIAL_CONDITIONS>
                <IC_MICRO x="10" v="0" />
                <IC_MICRO x="20" v="0" />
                <IC_MICRO x="30" v="0" />
                <IC_MICRO x="40" v="0" />
                <IC_MICRO x="50" v="0" />
                <IC_MICRO x="60" v="0" />
                <IC_MICRO x="70" v="0" />
                <IC_MICRO x="80" v="0" />
                <IC_MICRO x="90" v="0" />
                <IC_MICRO x="100" v="0" />
                <IC_MICRO x="110" v="0" />
                <IC_MICRO x="120" v="0" />
                <IC_MICRO x="130" v="0" />
                <IC_MICRO x="140" v="0" />
                <IC_MICRO x="150" v="0" />
                <IC_MICRO x="160" v="0" />
                <IC_MICRO x="170" v="0" />
                <IC_MICRO x="180" v="0" />
                <IC_MICRO x="190" v="0" />
                <IC_MICRO x="200" v="0" />
                <IC_MICRO x="210" v="0" />
                <IC_MICRO x="220" v="0" />
                <IC_MICRO x="230" v="0" />
                <IC_MICRO x="240" v="0" />
                <IC_MICRO x="250" v="0" />
                <IC_MICRO x="260" v="0" />
            </INITIAL_CONDITIONS>
            <TRAFFIC_SOURCE>
            </TRAFFIC_SOURCE>
            <TRAFFIC_SINK />
            <FLOW_CONSERVING_INHOMOGENEITIES>
            </FLOW_CONSERVING_INHOMOGENEITIES>
            <SPEED_LIMITS>
            </SPEED_LIMITS>
            <RAMPS>
            </RAMPS>
            <TRAFFIC_LIGHTS>
                <TRAFFIC_LIGHT x="1000" green_time="30"
                    green_red_time="3" red_time="200" red_green_time="2"
                    phase_shift="0" />
            </TRAFFIC_LIGHTS>

            <OUTPUT>
                <FLOATING_CAR_DATA n_dt="1" perc_out="0" dn="0">
                    <FC number="1" />
                    <FC number="5" />
                    <FC number="10" />
                    <FC number="15" />
                    <FC number="20" />
                </FLOATING_CAR_DATA>
            </OUTPUT>
        </ROAD>
    </SIMULATION>
</SCENARIO>

=== AKAIsmael/movsim/sim/startStop_IDMM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">


<!-- (c) Martin Treiber, Arne Kesting 2010      -->

<SCENARIO>

<DRIVER_VEHICLE_UNITS>

  <VEHICLE label="IDMM1" length="8" b_max="9"> 
    <LONGITUDINAL_MODEL>
       <IDM v0="15" T="1" s0="2" s1="0" delta="4" a="1.0" b="1.5" />
    </LONGITUDINAL_MODEL>
    <LANE_CHANGING_MODEL/>
	<MEMORY tau="600" alpha_v0="1" alpha_T="1.7" alpha_a="1" /> 
  </VEHICLE>
</DRIVER_VEHICLE_UNITS>



<OUTPUT>
  <FLOATING_CAR_DATA n_dt="5" perc_out="0" dn="0">
     <FC number="1" />
     <FC number="5" />
     <FC number="10" />
     <FC number="15" />
     <FC number="20" />
  </FLOATING_CAR_DATA>
</OUTPUT>

<SIMULATION dt="0.2" x_max="20000" t_max="360" lanes="1" with_fixed_seed="true" seed="42">

  <HETEROGENEITY write_fund_diagrams="true" >
    <VEHICLE_TYPE label="IDM1" fraction="1"  />
  </HETEROGENEITY>
  
  <INITIAL_CONDITIONS>
  <IC_MICRO x="10"  v="0" />  
  <IC_MICRO x="20"  v="0" />
  <IC_MICRO x="30"  v="0" />
  <IC_MICRO x="40"  v="0" />
  <IC_MICRO x="50"  v="0" />
  <IC_MICRO x="60"  v="0" />
  <IC_MICRO x="70"  v="0" />
  <IC_MICRO x="80"  v="0" />
  <IC_MICRO x="90"  v="0" />
  <IC_MICRO x="100" v="0" />
  <IC_MICRO x="110" v="0" />
  <IC_MICRO x="120" v="0" />
  <IC_MICRO x="130" v="0" />
  <IC_MICRO x="140" v="0" />
  <IC_MICRO x="150" v="0" />
  <IC_MICRO x="160" v="0" />
  <IC_MICRO x="170" v="0" />
  <IC_MICRO x="180" v="0" />
  <IC_MICRO x="190" v="0" />
  <IC_MICRO x="200" v="0" />
  <IC_MICRO x="210" v="0" />
  <IC_MICRO x="220" v="0" />
  <IC_MICRO x="230" v="0" />
  <IC_MICRO x="240" v="0" />
  <IC_MICRO x="250" v="0" />
  <IC_MICRO x="260" v="0" />
  </INITIAL_CONDITIONS>


  <UPSTREAM_BOUNDARY_CONDITIONS>
  </UPSTREAM_BOUNDARY_CONDITIONS>

  <FLOW_CONSERVING_INHOMOGENEITIES>
  </FLOW_CONSERVING_INHOMOGENEITIES>
  

  <SPEED_LIMITS>
  </SPEED_LIMITS>

  <RAMPS>
  </RAMPS>

  <TRAFFICLIGHTS>
     <TRAFFICLIGHT x="1000" green_time="30" green_red_time="3" red_time="200" red_green_time="2" phase_shift="0" /> 
  </TRAFFICLIGHTS>

</SIMULATION>

</SCENARIO>

=== AKAIsmael/movsim/sim/bookScenarioStartStop/startStop_ACC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "multiModelTrafficSimulatorInput.dtd">
<!-- (c) Martin Treiber, Arne Kesting 2010 -->
<SCENARIO network_filename="startStop.xodr">
    <FUEL_CONSUMPTION>
       <CONSUMPTION_MODEL label="carConsumption" >
       <CAR mass="1500" cross_section_surface="2.2" cd_value="0.32" electric_power="3000" const_friction="0.015" v_friction="0" dynamic_tyre_radius="0.31" />
       <ENGINE max_power_kW="90" cylinder_vol_l="1.4" idle_cons_rate_linvh="0.8" cspec_min_g_per_kwh="280" pe_min_bar="1" pe_max_bar="19"
             idle_rotation_rate_invmin="1000" max_rotation_rate_invmin="6000" >
       <GEAR_RATIOS>
         <GEAR_RATIO phi="16.7" />
         <GEAR_RATIO phi="10.1" />
         <GEAR_RATIO phi="6.8" />
         <GEAR_RATIO phi="5.0" />
         <GEAR_RATIO phi="3.8" />
         <GEAR_RATIO phi="3.1" />
         <GEAR_RATIO phi="2.6" />
       </GEAR_RATIOS>
       </ENGINE>
       </CONSUMPTION_MODEL>
    </FUEL_CONSUMPTION>
    <VEHICLES>
        <VEHICLE label="ACC1" length="8" b_max="9" consumption="carConsumption">
            <LONGITUDINAL_MODEL>
                <ACC v0="15" T="1.2" s0="2" s1="0" delta="4" a="1.5" b="1.5" coolness="1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
        <VEHICLE label="Obstacle" length="0">
            <LONGITUDINAL_MODEL>
                <IDM v0="0" T="1" s0="2" a="1.0" b="1.5"/>
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL/>
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="0.2" duration="360" seed="42">
        <TRAFFIC_COMPOSITION write_fund_diagrams="true">
            <VEHICLE_TYPE label="ACC1" fraction="1" />
        </TRAFFIC_COMPOSITION>
        <ROAD id="1">
            <INITIAL_CONDITIONS>
                <IC_MICRO  x="10" v="0" />
                <IC_MICRO  x="20" v="0" />
                <IC_MICRO  x="30" v="0" />
                <IC_MICRO  x="40" v="0" />
                <IC_MICRO  x="50" v="0" />
                <IC_MICRO  x="60" v="0" />
                <IC_MICRO  x="70" v="0" />
                <IC_MICRO  x="80" v="0" />
                <IC_MICRO  x="90" v="0" />
                <IC_MICRO x="100" v="0" />
                <IC_MICRO x="110" v="0" />
                <IC_MICRO x="120" v="0" />
                <IC_MICRO x="130" v="0" />
                <IC_MICRO x="140" v="0" />
                <IC_MICRO x="150" v="0" />
                <IC_MICRO x="160" v="0" />
                <IC_MICRO x="170" v="0" />
                <IC_MICRO x="180" v="0" />
                <IC_MICRO x="190" v="0" />
                <IC_MICRO x="200" v="0" />
                <IC_MICRO x="210" v="0" />
                <IC_MICRO x="220" v="0" />
                <IC_MICRO x="230" v="0" />
                <IC_MICRO x="240" v="0" />
                <IC_MICRO x="250" v="0" />
                <IC_MICRO x="260" v="0" />
            </INITIAL_CONDITIONS>
            <TRAFFIC_SOURCE />
            <TRAFFIC_LIGHTS>
                <TRAFFIC_LIGHT x="1000" green_time="30" green_red_time="3" red_time="200" red_green_time="2" phase_shift="0" />
            </TRAFFIC_LIGHTS>
        </ROAD>
        <OUTPUT>
            <FLOATING_CAR_DATA n_dt="5" perc_out="0" dn="0">
                <FC number="1" />
                <FC number="5" />
                <FC number="10" />
                <FC number="15" />
                <FC number="20" />
            </FLOATING_CAR_DATA>
        </OUTPUT>
    </SIMULATION>
</SCENARIO>

=== AKAIsmael/movsim/src/main/resources/sim/startStop_KCA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">

<!-- (c) Martin Treiber, Arne Kesting 2010      -->

<SCENARIO>

<DRIVER_VEHICLE_UNITS>

   <!-- vehicle length ==> cell units --> 
   <VEHICLE label="KCA1" length="20" >   
     <LONGITUDINAL_MODEL>
  	 <KCA v0="28" k="2.55" pb0="0.425" pb1="0.04" pa1="0.2" pa2="0.052" vp="14"  />  <!-- lambda="0.55" ? -->
     </LONGITUDINAL_MODEL>
     <LANE_CHANGING_MODEL/>
   </VEHICLE>
   
   <VEHICLE label="Obstacle" length="20" >  
     <LONGITUDINAL_MODEL>
	  <KCA v0="0" k="2.55" pb0="0.425" pb1="0.04" pa1="0.2" pa2="0.052" vp="14"  />  <!-- lambda="0.55" ? -->
     </LONGITUDINAL_MODEL>
     <LANE_CHANGING_MODEL/>
   </VEHICLE>

</DRIVER_VEHICLE_UNITS>



<OUTPUT>
  <FLOATING_CAR_DATA  n_dt="1" perc_out="0" dn="0">
     <FC number="1" /> <!-- is obstacle -->
     <FC number="2" />
     <FC number="6" />
     <FC number="11" />
     <FC number="16" />
     <FC number="21" />
  </FLOATING_CAR_DATA>
</OUTPUT>

<!-- depends strongly on randomness resp. seed !!! --> 
<SIMULATION dt="1" x_max="20000" t_max="360" lanes="1" with_fixed_seed="true" seed="50">
  <HETEROGENEITY write_fund_diagrams="true" >
    <VEHICLE_TYPE label="KCA1" fraction="1"  />
	<VEHICLE_TYPE label="Obstacle" fraction="0"  />
  </HETEROGENEITY>
  
  <INITIAL_CONDITIONS>
  <IC_MICRO x="20"  v="0" label="KCA1" />  
  <IC_MICRO x="40"  v="0" label="KCA1" />
  <IC_MICRO x="60"  v="0" label="KCA1" />
  <IC_MICRO x="80"  v="0" label="KCA1" />
  <IC_MICRO x="100"  v="0" label="KCA1" />
  <IC_MICRO x="120"  v="0" label="KCA1" />
  <IC_MICRO x="140"  v="0" label="KCA1" />
  <IC_MICRO x="160"  v="0" label="KCA1" />
  <IC_MICRO x="180"  v="0" label="KCA1" />
  <IC_MICRO x="200" v="0" label="KCA1" />
  <IC_MICRO x="220" v="0" label="KCA1" />
  <IC_MICRO x="240" v="0" label="KCA1" />
  <IC_MICRO x="260" v="0" label="KCA1" />
  <IC_MICRO x="280" v="0" label="KCA1" />
  <IC_MICRO x="300" v="0" label="KCA1" />
  <IC_MICRO x="320" v="0" label="KCA1" />
  <IC_MICRO x="340" v="0" label="KCA1" />
  <IC_MICRO x="360" v="0" label="KCA1" />
  <IC_MICRO x="380" v="0" label="KCA1" />
  <IC_MICRO x="400" v="0" label="KCA1" />
  <IC_MICRO x="420" v="0" label="KCA1" />
  <IC_MICRO x="440" v="0" label="KCA1" />
  <IC_MICRO x="460" v="0" label="KCA1" />
  <IC_MICRO x="480" v="0" label="KCA1" />
  <IC_MICRO x="500" v="0" label="KCA1" />  <!-- FC number 2 -->
  <IC_MICRO x="2000" v="0" label="Obstacle"/> <!-- shifts floating car numbers -->
  </INITIAL_CONDITIONS>


  <UPSTREAM_BOUNDARY_CONDITIONS>
  </UPSTREAM_BOUNDARY_CONDITIONS>

  <FLOW_CONSERVING_INHOMOGENEITIES>
  </FLOW_CONSERVING_INHOMOGENEITIES>
  

  <SPEED_LIMITS>
  </SPEED_LIMITS>

  <RAMPS>
  </RAMPS>

  <TRAFFICLIGHTS>
     <!-- not implemented for CA -->
  </TRAFFICLIGHTS>

</SIMULATION>

</SCENARIO>

=== AKAIsmael/movsim/sim/onramp_KKW.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">
<!-- (c) Martin Treiber, Arne Kesting 2011 -->
<SCENARIO path="." >
    <VEHICLES>
       <!-- vehicle length ==> cell units -->
        <VEHICLE label="KKW1" length="15">
            <!-- b_max not limited -->
            <LONGITUDINAL_MODEL>
              <KKW v0="67" k="2.55" pb0="0.425" pb1="0.04" pa1="0.2" pa2="0.052" vp="28" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="1" duration="7200" fixed_seed="true" seed="42" crash_exit="false" >
         <!-- scaled units for time and space -->
        <ROAD id="1" length="40000" lanes="1">
            <TRAFFIC_COMPOSITION write_fund_diagrams="true">
                <VEHICLE_TYPE label="KKW1" fraction="1" />
            </TRAFFIC_COMPOSITION>
            <INITIAL_CONDITIONS>
                <IC_MACRO x="2000" rho_per_km="2" v="3" />
            </INITIAL_CONDITIONS>
            <TRAFFIC_SOURCE logging="true">
                <INFLOW t="0" q_per_hour="100"    v="110" />
                <INFLOW t="600" q_per_hour="2000" v="90" />
            </TRAFFIC_SOURCE>
            <TRAFFIC_SINK />
            <!-- improve vehicle performance at inflow -->
            <FLOW_CONSERVING_INHOMOGENEITIES />
            <SPEED_LIMITS/>
            <RAMPS>
                <!-- scaled units! -->
                <SIMPLE_RAMP x="30000" length="1000" logging="true">
                    <INFLOW t="0" q_per_hour="550" />
                </SIMPLE_RAMP>
            </RAMPS>
            <TRAFFIC_LIGHTS>
            </TRAFFIC_LIGHTS>
            <DETECTORS dt="60" logging="true">
                <CROSS_SECTION x="16000" />
                <CROSS_SECTION x="18000" />
                <CROSS_SECTION x="20000" />
                <CROSS_SECTION x="22000" />
                <CROSS_SECTION x="24000" />
                <CROSS_SECTION x="26000" />
                <CROSS_SECTION x="28000" />
                <CROSS_SECTION x="30000" />
                <CROSS_SECTION x="32000" />
             </DETECTORS>
        </ROAD>
        <OUTPUT>
           <SPATIOTEMPORAL dx="200" dt="40" />
        </OUTPUT>
    </SIMULATION>
</SCENARIO>

=== AKAIsmael/movsim/sim/tests/onramp/onramp_IDM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "sim/multiModelTrafficSimulatorInput.dtd">
<SCENARIO network_filename="onramp.xodr">
    <VEHICLES>
        <VEHICLE label="IDM1" length="6" b_max="9">
            <LONGITUDINAL_MODEL>
                <IDM v0="35" T="1.2" s0="2" s1="0" delta="4" a="1.2" b="2.0"/>
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="false" crit_speed_eur="20">
                <MOBIL b_safe="5.0" s_min="2.0" threshold="0.1" bias_right="0.05" politeness="0.1"/>
            </LANE_CHANGE_MODEL>
        </VEHICLE>
        <!-- trucks -->
        <VEHICLE label="IDM2" length="6" b_max="9">
            <LONGITUDINAL_MODEL>
                <IDM v0="35" T="1.2" s0="2" s1="0" delta="4" a="1.2" b="2.0"/>
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="false" crit_speed_eur="20">
                <MOBIL b_safe="5.0" s_min="2.0" threshold="0.1" bias_right="0.3" politeness="0.1"/>
            </LANE_CHANGE_MODEL>
        </VEHICLE>
        <VEHICLE label="Obstacle" length="0">
            <LONGITUDINAL_MODEL>
                <IDM v0="0" T="1" s0="2" a="1.0" b="1.5"/>
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL/>
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="0.2" duration="2400" fixed_seed="true" seed="42" crash_exit="true">
        <TRAFFIC_COMPOSITION write_fund_diagrams="false">
            <VEHICLE_TYPE label="IDM1" fraction="0.8" relative_v0_randomization="0.2"/>
            <VEHICLE_TYPE label="IDM2" fraction="0.2" relative_v0_randomization="0.2"/>
        </TRAFFIC_COMPOSITION>
        <ROAD id="1">
            <TRAFFIC_SOURCE logging="true">
                <INFLOW t="0" q_per_hour="1600" v="24"/>
            </TRAFFIC_SOURCE>
        </ROAD>
        <ROAD id="4">
            <TRAFFIC_SOURCE logging="true">
                <INFLOW t="0" q_per_hour="300" v="20"/>
            </TRAFFIC_SOURCE>
        </ROAD>
        <OUTPUT>
            <FLOATING_CAR_DATA n_dt="1">
                <FC number="280" />
                <FC number="281" />
                <FC number="1170" />
                <FC number="1171" />
                <FC number="1172" />
                <FC number="1173" />
                <FC number="1174" />
                <FC number="1175" />
                <FC number="1176" />
                <FC number="1177" />
                <FC number="1178" />
                <FC number="1179" />
            </FLOATING_CAR_DATA>
        </OUTPUT>
    </SIMULATION>
</SCENARIO>
